### ISSUE TITLE
`<pdf:pagenumber>` and `<pdf:pagecount>` causes page number to be printed twice

### ISSUE THREAD

**Issue by commx** [xhtml2pdf/xhtml2pdf#106]
I have strange issues with the above tags inside html templates.

Let's say I have `<div id="footer_pagenumber">Page <pdf:pagenumber/></div>` then the page number is printed twice (11 instead of 1). If I add a single whitespace after the `<pdf:pagenumber/>` tag, the number is fine. The same problem applies to `<pdf:pagecount/>`.

Another issue is with `<pdf:pagecount/>` is that if I use this tag, the background image of my PDF is not rendered anymore.

Tested with xhtml2pdf v0.0.5, reportlab 2.7 and Pillow 2.0.0.

**Comment by MaoAiz** [comment]
+1 I have the same problem with the <pdf:pagecount> tag. It's show 11 instead of 1, or 22 instead of 2.

**Comment by johnfraney** [comment]
+1. Tested with `xhtml2pdf 0.0.6` and `reportlab 2.7`

**Comment by pavlix** [comment]
I also experience it but I found a workaround. It was good enough to put one space just after the tag, i.e. change `<pdf:pagenumber>` to `<pdf:pagenumber> `.

**Comment by w-** [comment]
+11

**Comment by citizen-stig** [comment]
+1

**Comment by benjaoming** [comment]
To anyone bothered by this issue and thinking _it's very old, silly and simple, yet no one is solving it, proving that this project is abandoned_: **NO!**

Please feel encouraged to resolve the issue in the `develop` branch, your improvements shall be noted, merged and released! This project is far from dead, and has had both issues fixed and new features implemented. However the community-led idea will only take flight when people step up, and we need that for a 0.1 release to happen within the next months :)

**Comment by w-** [comment]
I looked through the code but don't really understand where the issue might be taking place. 
I imagine it is probably here, but not sure as I don't understand what is going on
https://github.com/xhtml2pdf/xhtml2pdf/blob/master/xhtml2pdf/xhtml2pdf_reportlab.py#L269

**Comment by boevgeny** [comment]
my test case, "Page 1 of 5":

code: `<div id="header">Page <pdf:pagenumber> of <pdf:pagecount></div>`
result: `Page 1 of 55`
code: `<div id="header">Page <pdf:pagenumber></div>`
result: `Page 11`

but there is a solution:
code: `<div id="header">Page <pdf:pagenumber> of <pdf:pagecount> </div>`
result: `Page 1 of 5`
and
code: `<div id="header">Page <pdf:pagenumber> </div>`
result: `Page 1`

**Comment by alfonso-feria** [comment]
Un parche que soluciona, pero no es la manera correcta, es ocultar el segundo pdf:pagecount, ya que por lo visto el ultimo se esta repitiendo dando como resultado 1 de N

Página <pdf:pagenumber> de <pdf:pagecount> <pdf:pagecount style='display:none'>

**Comment by marioguima** [comment]
to "_correct_" just put **&nbsp;**
**&nbsp;** => this is the encode space
<pdf:pagenumber> of <pdf:pagecount>**&nbsp;**

**Comment by haruanm** [comment]
I have the same issues.
The the space after the pagecount does not fix the background issue.
I'm using python 3.8 with xhtml2pdf 0.2.5

**Comment by CaetanoGS** [comment]
I downgrade the library version and it worked for me.

I was using xhtml2pdf==0.2.5 and now I am using xhtml2pdf==0.2.3

**Comment by michal-stachura** [comment]
+1
Adding white space solve problem

**Comment by felikjunvianto** [comment]
@luisza thank you for picking up this old issue!

**Comment by w-** [comment]
unbelievable. i never thought i would see the day.
and for the fix to be so succint.

i no longer use this library but thx @JanEgner
