### ISSUE TITLE
DeprecationWarning: tostring() is deprecated.

### ISSUE THREAD

**Issue by boromil** [xhtml2pdf/xhtml2pdf#122]
When using xhtml2pdf==0.0.5 with django 1.5.1 I get the following deprecation warning:
>xhtml2pdf/xhtml2pdf_reportlab.py:422: DeprecationWarning: tostring() is deprecated. Please call tobytes() instead.
>  self._data = im.tostring()

This should be an easy fix :)

**Comment by benjaoming** [comment]
Some 3 years later... thanks friend :)
