### ISSUE TITLE
Ol Tag CSS Counting Broken

### ISSUE THREAD

**Issue by firewut** [xhtml2pdf/xhtml2pdf#13]
CSS Style
<pre>
ol{counter-reset: section;} 
ol li{counter-increment: section;} 
ol li:before{content: counters(section, ".") " ";}
</pre>

Example Code: 
<pre>
<ol>
        <li>item 1
            <ol>
                <li>sub item 1
                    <ol>
                        <li>sub-sub item 1</li>
                        <li>sub-sub item 2</li>
                        <li>sub-sub item 3</li>
                    </ol>
                 </li>
                 <li>Sub item 2</li>
             </ol>
         </li>
         <li>item 2</li>
</ol>
</pre>

I Need this
<pre>
1 item 1
        1.1 sub item 1
                1.1.1 sub-sub item 1
                1.1.2 sub-sub item 2
                1.1.3 sub-sub item 3
        1.2 Sub item 2
2 item 2
</pre>

But I'm getting this
<pre>
1 item 1
        1 sub item 1
                1 sub-sub item 1
                2 sub-sub item 2
                3 sub-sub item 3
        2 Sub item 2
2 item 2
</pre>

Is There A Cure ? :)

**Comment by benjaoming** [comment]
Please consider expressing this more "refined" logic in the code where you are generating the HTML.

Contributions that expand our CSS functionality are welcome, but we cannot have an issue for each XYZ subset of CSS 3 that isn't supported.
