### ISSUE TITLE
problem wihle converting unicode to pdf

### ISSUE THREAD

**Issue by beebek** [xhtml2pdf/xhtml2pdf#130]
In this simple example the unicode get converted to some gibrish codes. Am I missing something??
# coding: utf-8

from xhtml2pdf import pisa

sourceHtml = u'सरल'
fd = open("temp_file.pdf", "w+b")
pisaStatus = pisa.CreatePDF(sourceHtml.encode('utf8'), dest=fd)
fd.close()

**Comment by ninenox** [comment]
I have problem same you. I use thai language.
![pdf](https://cloud.githubusercontent.com/assets/12573570/8058477/f1e4490c-0ee3-11e5-9647-4946594c222f.png)

**Comment by SimonAstani** [comment]
> A absolute path to src url was required. Cheers
> 
> source = """
> <style>
> @font-face {
> font-family: Preeti;
> src: url("C:/project/static/fonts/preeti.ttf");
> }
> 
> ```
>                 body {
>                 font-family: Preeti;
>                 }
>             </style>
>             <body>
>                 This is a test <br/>
>                        सरल
>             </body>
>         </html>"""
> ```
what if we have multiple language support in a single print. This approach converts all fonts to specified font family..
