### ISSUE TITLE
CSS parser can't deal with "@media screen and (max-width: 960px)"

### ISSUE THREAD

**Issue by khink** [xhtml2pdf/xhtml2pdf#132]
Feeding "@media screen and (max-width: 960px) {...}" into cssParser.py _parseAtMedia breaks: "@media rule expected media identifier"

**Comment by benjaoming** [comment]
Should be fine, tested with:

```
 @media screen and (min-width: 480px) {
    body {
        background-color: lightgreen;
    }
}
```
