### ISSUE TITLE
CSS doesn't work for ULs

### ISSUE THREAD

**Issue by demiurg** [xhtml2pdf/xhtml2pdf#138]
Hi, I tried to find out any information on the limitation of CSS selectors but didn't find anything by a list of properties supported. I have an an example of simple CSS styling all ul's but it seems to work only for first one. Other features like class selector doesn't seem to work at all. I don't know if it is an issue or I missed something about these limitations in the docs.

Here is my self-contained html:
https://gist.github.com/demiurg/7029596

xhtml2pdf version 0.0.5 for me outputs inconsistently styles lists using weird boldness for everything after first list and no font size change.

**Comment by aidan2129** [comment]
`<ul>` is a unordered list not under line if you want to underline your content just use `<u>`

**Comment by aidan2129** [comment]
@demiurg

**Comment by benjaoming** [comment]
Closing this due to it's age and the substantial changes in the codebase since then.

**Comment by benjaoming** [comment]
Also, for reference: The linked document renders quite okay, it's a bit hard to know exactly what the intended output is, but I'd say what I see looks plausible.

![screenshot from 2016-04-19 13 02 39](https://cloud.githubusercontent.com/assets/374612/14637001/04eed1fa-062f-11e6-8f2d-f86b7eb78d0a.png)

**Comment by aidan2129** [comment]
When i tried to render the <ul> it just looked like a paragraph for example

`            <ul>
            <li>test</li>
            <li>test</li>
            <li>test</li>
            <li>test</li>
            </ul>`

becomes "test test test test"

**Comment by benjaoming** [comment]
Works for me, are you sure you're using the dev version?
