### ISSUE TITLE
new user can't find command line utility after install

### ISSUE THREAD

**Issue by bertdouglas** [xhtml2pdf/xhtml2pdf#144]
Hi All,

I followed the instructions in "readme.rst" on the project main page.  Everything went perfect.  Did the "nosetests --with-coverage" at step 7.  That gave expected result.

Now how do I invoke xhtml2pdf as a command line tool ?  According to "doc/usage.rst" I can invoke from the command line as:

$ xhtml2pdf test.html

But I have searched my entire filesystem and there is no such file as "xhtml2pdf".
I am using debian 7.

Thanks much,
Bert Douglas

**Comment by ruv** [comment]
I have the same issue. Deactivating and activating virtualenv doesn't help. How to fix or maybe narrow this issue?

**Comment by ruv** [comment]
The issue was resolved after running:
```
./setup.py build
./setup.py install
```
in xhtml2pdf directory.
