### ISSUE TITLE
@page size portrait warning

### ISSUE THREAD

**Issue by petef4** [xhtml2pdf/xhtml2pdf#149]
According to usage.rst @page size can take an orientation component of portrait or landscape. The code in context.py only accepts landscape; portrait does work but logs a warning.

WARNING:xhtml2pdf:Unknown size value for @page

atPage() should have another clause in its tests for valueStr, if it equals "portrait" set isLandscape to False.

**Comment by jjgumucio** [comment]
Is this project still active? 
I have the same issue.

**Comment by benjaoming** [comment]
Not seeing the warning message anymore.

**Comment by diegobill** [comment]
same problem, but it is not a warning, it is an error for me

**Comment by diegobill** [comment]
I found the solution, you have to use dot comma in the css, like this:

```
            <style> 
            @page {
                size: letter landscape;
                margin: 1cm;
            } 
            </style>
```
