### ISSUE TITLE
Unable to render Base64 CSS Font.

### ISSUE THREAD

**Issue by plamen-nikolov** [xhtml2pdf/xhtml2pdf#153]
I am trying to embed base64 font in my HTML, but the library can load it. I made some research and found that in file util.py:519 there is a condition that checks if the uri starts with "data:", but the passed uri is a list, that is evaluated to str, so the string is "[u'data:..'" and the if can match it. I tried couple of tricky things, but after the match another errors came out. So, can you help me guys to fix this issue? Thanks a lot!

```
# Data URI
        if uri.startswith("data:"): # uri="[u'data:....']"
            m = _rx_datauri.match(uri)
            self.mimetype = m.group("mime")
            self.data = base64.decodestring(m.group("data"))
```

That is how my html file looks like:

```
@font-face {
                font-family: "Trebuchet MS";
                font-style: normal;
                font-weight: normal;
                src: url(data:font/truetype;base64,AAEA......) format('truetype');
}
```

**Comment by ho9science** [comment]
your os don't have type 'font/ttf', add mime type in os

**Comment by jhahn3** [comment]
I am also attempting to use the font face with base 64 true type.  I have followed the above from plamen-nikolov and am getting an error:

@font-face{
        font-family: burton;
        src: url('data:font/truetype;charset=utf-8;base64,<<BASE64>>') format('truetype');
}

ERROR: Extract data form data: in tag

I have tried many different iterations of this, but am not having any luck.  Can someone please help?
