### ISSUE TITLE
Issue with drawing background image for landscape page orientation.

### ISSUE THREAD

**Issue by kgrodzicki** [xhtml2pdf/xhtml2pdf#17]
Generation of the background image for landscape page orientation is currently broken.

**Comment by alainpoeta** [comment]
I have a problem with background-image for landscape page
size: A4 landscape;

but the backgroud-image is in portrait format

**Comment by githubdoramon** [comment]
I am still unable to use background images for landscape positioning. Does anyone can help me with that?

If I set the page for portrait it works normally
