### ISSUE TITLE
Footer frames in landscape pages

### ISSUE THREAD

**Issue by tanoc** [xhtml2pdf/xhtml2pdf#19]
Bottom aligned frames are positioned outside the page if the document is in landscape.

```
<html>
<style>
@page {
  margin: 1cm;
  margin-bottom: 2.5cm;
  size: A4 landscape; 
  @frame footer {
    -pdf-frame-content: footerContent;
    bottom: 2cm;
    margin-left: 1cm;
    margin-right: 1cm;
    height: 1cm;
  }
}
</style>
<body>
  Some text
  <div id="footerContent">
    This is a footer on page #<pdf:pagenumber>
  </div>
</body>
</html>
```

probably because the frame position is calculated with `c.pageSize` still in portrait

https://github.com/chrisglass/xhtml2pdf/blob/master/xhtml2pdf/context.py#L325

**Comment by benjaoming** [comment]
Reported issue cannot be confirmed anymore.
