### ISSUE TITLE
Does xhtml2pdf support Python3.3? 

### ISSUE THREAD

**Issue by sgeoffrey** [xhtml2pdf/xhtml2pdf#190]
we are moving our projects to python 3, does xhtml2pdf support python 3?

**Comment by GildedHonour** [comment]
I'm working on it at https://github.com/GildedHonour/xhtml2pdf-py3

**Comment by ebar0n** [comment]
Longer supported, I've used python django 3.4 and 1.7.

work at https://github.com/ebar0n/xhtml2pdf and already updated the main repository https://github.com/chrisglass/xhtml2pdf

**Comment by JimInCO** [comment]
The code in the main repository is not python 3 compatible. At least one of the packages specified in [requirements.txt](https://github.com/chrisglass/xhtml2pdf/blob/master/requirements.txt) do not work in Python 3 (reportlab==2.5).

When I run the command:
    nosetests

I get [four errors](https://gist.github.com/JimInCO/c107b45db35faf4b0627) on my machine.

**Comment by taddeimania** [comment]
:+1:

**Comment by ebar0n** [comment]
I use reportlab == 3.0, these days, I returned to supports the file requerimientos.txt not actualize as there are many using python 2.7

For my part libraria use smoothly under python 3.4 in my Django project

Upgrade reportlab apart, anything you mention me.

**Comment by alfaro28** [comment]
Hi, 
I'm getting this error:

Exception Value: 	string argument expected, got 'bytes'
Exception Location: 	/mypath/python3.4/site-packages/xhtml2pdf/document.py in pisaDocument, line 184

Any help is much appreciated

**Comment by benjaoming** [comment]
The development version supports Python 3, albeit not necessarily Python 3.3 as I don't think that's a widespread version anymore.

I regret that we don't have better documentation of the usage, but I invite everyone to use the latest alpha with Python 3 and make PRs that fix their issues.

Other than that, please rest assured that xhtml2pdf is in production in a lot of systems and is not broken as such, it just needs a kind loving hand :)
