### ISSUE TITLE
Font-embedding regression in xhtml2pdf 0.0.6

### ISSUE THREAD

**Issue by mziab** [xhtml2pdf/xhtml2pdf#195]
After upgrading to xhtml2pdf 0.0.6, embedding fonts using @font-face doesn't work anymore. The logs show no related debug messages. The font is just not embedded. The same code used to work perfectly with xhtml2pdf 0.0.5 and the link_callback returns a valid font path.

I was able to bisect it to this commit:

87c63ab9414ad0cc3b5c3a5af402a86ac7d1b964 is the first bad commit
commit 87c63ab9414ad0cc3b5c3a5af402a86ac7d1b964
Author: Andreas Stocker <andreas.stocker@xhostplus.at>
Date:   Thu Aug 1 09:33:11 2013 +0200

    findCSSRuleFor should return the actual values not StopIteration objects, returning the right order of rule-sets

:040000 040000 820d1309a9eabe9d1c0bce4c7929556e2a6411d1 9289174f05f9b7c16f4f557f936b028ab4733e8b M      xhtml2pdf

**Comment by benjaoming** [comment]
I suspect this is fixed in #199 - if this is not the case, let's reopen and reinvestigate.

**Comment by benjaoming** [comment]
...and #204 possibly also fixes it
