### ISSUE TITLE
Repeat page_header on all page

### ISSUE THREAD

**Issue by jayapal** [xhtml2pdf/xhtml2pdf#198]
I am using xhtml2pdf in my Django project and facing  issue which i listed below. Can you just help out?
1.  How to repeat header(page_header) in all page. (https://github.com/chrisglass/xhtml2pdf/blob/master/demo/djangoproject/templates/base.html) since as per your example, I am able to get the header in first page and footer in all page but not header.

Thnks for your time.

**Comment by benjaoming** [comment]
Stuff like this: Put it on StackOverflow.
