### ISSUE TITLE
Error using django demo example

### ISSUE THREAD

**Issue by rougeth** [xhtml2pdf/xhtml2pdf#216]
Using django 1.7 py3, I tried the function `render_to_pdf` [django demo example](https://github.com/chrisglass/xhtml2pdf/blob/master/demo/djangoproject/views.py#L49-L60) and got the following error:

`Exception Value: string argument expected, got 'bytes'`

When I pass a simple string, like `'hello world'`, it says that `name 'unicode' is not defined`. I believe it's a python 3 port issue.

**Comment by reb00ter** [comment]
had same issue
in util.py: 508 changed encoding to latin1
in document.py after line 171 added
    if type(data) is str:
        data = data.encode(encoding='UTF-8')
now getting blank doc without errors

**Comment by reb00ter** [comment]
https://github.com/chrisglass/xhtml2pdf/issues/190#issuecomment-73881932

**Comment by honzap** [comment]
Thanks for hints. I've fixed encoding in util.py and in document.py, before writing to buffer, encode the str again to bytes.
```
if type(data) is str:
        data = data.encode('latin1')
```
Now, it seems the generating works with python3 for me with simple document example...attaching freeze:
````
$ pip3 freeze
Django==1.8.2
Pillow==2.8.2
PyJWT==1.3.0
PyPDF2==1.24
defusedxml==0.4.1
django-easy-pdf==0.1.0
html5lib==0.99999
oauthlib==0.7.2
psycopg2==2.6
reportlab==3.2.0
xhtml2pdf==0.0.6
```

**Comment by kensonman** [comment]
I got the similar problems. The exception log is:
  File "/usr/local/lib/python3.4/site-packages/xhtml2pdf/document.py", line 184, in pisaDocument
    context.dest.write(data)  # TODO: context.dest is a tempfile as well...
TypeError: string argument expected, got 'bytes'
[21/Mar/2016 12:16:20] "POST /scheduler/reports/calendars/ HTTP/1.1" 500 106774
 

I'm using xhtml2pdf-0.1a1

**Comment by benjaoming** [comment]
Hi all,

@kensonman as @reb00ter noted, you need to feed `CreatePDF` unicode data and encode is as such, too.

I regret that we don't have better documentation, but I invite everyone to use the latest alpha with Python 3 and make PRs that fix their issues.

Other than that, please rest assured that xhtml2pdf is in production in a lot of systems and is not broken as such, it just needs a kind loving hand :)
