### ISSUE TITLE
Background color not set in table cells

### ISSUE THREAD

**Issue by bmihelac** [xhtml2pdf/xhtml2pdf#219]
Notice that my stylesheets does not work when I upgraded to master.

Running cmd below on master yields blank document:

```
python pisa.py -d testrender/data/source/simple-test.html test.pdf
```

Latest commit when I receive valid pdf from testrender sources is a93c5bd7422c9b26bfe5a464756e135f68956624.

**Comment by bmihelac** [comment]
Also test-tables example is rendered very differently from reference:

https://github.com/chrisglass/xhtml2pdf/blob/master/testrender/data/reference/test-tables.page0.png
https://github.com/chrisglass/xhtml2pdf/blob/master/testrender/data/reference/test-tables.page1.png

vs

![test-tables](https://cloud.githubusercontent.com/assets/13813/6441661/581a1db6-c0ea-11e4-86eb-413e220274e9.png)
![test-tables1](https://cloud.githubusercontent.com/assets/13813/6441660/58192942-c0ea-11e4-9013-0267b718331e.png)

**Comment by benjaoming** [comment]
After fixing a slight bug in the command, I'm now getting this result on Python 2 with the latest `develop` branch.

Reference:
![simple-test page0](https://cloud.githubusercontent.com/assets/374612/14635807/5089d508-0628-11e6-83b0-3c0a1536db53.png)

Result:
![screenshot from 2016-04-19 12 15 08](https://cloud.githubusercontent.com/assets/374612/14635820/61d123fc-0628-11e6-89f5-328d7c3aa033.png)

**Comment by benjaoming** [comment]
It seems that it's only background colors that are broken...

Reference:

![test-tables page1](https://cloud.githubusercontent.com/assets/374612/14635898/b5081cf6-0628-11e6-8bb1-594f0373b9a3.png)

Result:
![screenshot from 2016-04-19 12 17 59](https://cloud.githubusercontent.com/assets/374612/14635913/c79289c4-0628-11e6-8791-0f33b910a00e.png)

**Comment by benjaoming** [comment]
This is the only real big problem left before all the testrender examples will comply with expected results.... and hence I've added it to the 0.1 final milestone.

Anybody wanna take this on? :)

**Comment by fbernhart** [comment]
Seems like this has already been fixed. I just rendered the test-tables.html file. Results look like expected with Python 3.8 and Python 3.9:

[Test.pdf](https://github.com/xhtml2pdf/xhtml2pdf/files/5347359/Test.pdf)

My guess would be: This as well had to do with the insertion order of dictionaries in Python < 3.6. See #299

So this issue can be closed.
