### ISSUE TITLE
requirements.txt not in distrib package.

### ISSUE THREAD

**Issue by catonic** [xhtml2pdf/xhtml2pdf#22]
requirements.xml is not distributed in the downloadable package: 
http://pypi.python.org/pypi/xhtml2pdf/

https://github.com/chrisglass/xhtml2pdf:

"
file 	requirements.xml 	July 14, 2011 	added requirements file [kgrodzicki] "

...

"Next step will be to install/upgrade dependencies from requirements.txt file:

pip install -r requirements.txt"

Installation documentation incorrect, inaccurate, or out of date:

1) requirements.txt isn't distributed in 
http://pypi.python.org/packages/source/x/xhtml2pdf/xhtml2pdf-0.0.3.tar.gz#md5=13b0d6059b72c994473fddfa7a528451
from http://pypi.python.org/pypi/xhtml2pdf/. http://pypi.python.org/pypi/xhtml2pdf/ documentation is identical to https://github.com/chrisglass/xhtml2pdf. 

2) requirements.txt is actually requirements.xml. 

3) requirements.xml isn't distributed in the above linked package. 

4) requirements.xml doesn't contain information parsable by the above listed installation method.

**Comment by benjaoming** [comment]
This should all be good now!
