### ISSUE TITLE
support for Python3

### ISSUE THREAD

**Issue by Gaurav-t** [xhtml2pdf/xhtml2pdf#223]
I'll try to move my project from python2 to python3, Is xhtml2pdf - 0.0.6 works with python3?

**Comment by JimInCO** [comment]
It does not work with Python 3. Right now the master branch of this repository does not work for Python 3 either, #190.
There have been a number of pull requests for Python 3 support, #177, #205, #222. Thus far none have been merged with the main branch.

**Comment by xj9** [comment]
We have an active fork at [zulumarketing/html2pdf][1]; would you mind opening an issue over there too?

We haven't made any releases yet, but we have made a lot of progress modernizing the codebase (in particular, we've managed to get it working on Py3k), and we would love to hear what broken bits the community would like to help us fix, and what y'all would like to see *us* fix.

I've opened an [issue][2] specifically to discuss where this library needs to change and what the roadmap will look like.

[1]: https://github.com/zulumarketing/html2pdf
[2]: https://github.com/zulumarketing/html2pdf/issues/4

**Comment by ebar0n** [comment]
Check the main branch, for one gave support you need to run the library Python 3, the low use django projects and works as it should. agregu again recently an update, because some are not careful with climbing.

Sorry for my bad English.

**Comment by benjaoming** [comment]
Please have a look at the 'develop' branch and open up specific issues for all bugs encountered with Python 3.

We are heading away from the 'holistic' python3 support approach and now acting as if we have it, and everything that doesn't work is an issue of its own.

Will prerelease soon as 0.1alpha1.
