### ISSUE TITLE
NameError: global name 'pisa' is not defined

### ISSUE THREAD

**Issue by vyscond** [xhtml2pdf/xhtml2pdf#226]
You missed the part telling where the hell this pisa is comming.
https://github.com/chrisglass/xhtml2pdf/blob/master/doc/usage.rst#using-xhtml2pdf-in-django

**Comment by halfnibble** [comment]
from xhtml2pdf import pisa

**Comment by oscarshaitan** [comment]
when i put from xhtml2pdf import pisa the error : 'No module named xhtml2pdf' shows up and i follow all the  Using xhtml2pdf usage.rst and import the pisa too
