### ISSUE TITLE
pdfs are badly formatted

### ISSUE THREAD

**Issue by ghandee** [xhtml2pdf/xhtml2pdf#227]
I use it as a pdf renderer for pyramid framework and from time to time generated document's stucture is strange.

From time to time == I can create same document 49 times and when I do it once more this bug occurs (paragraphs are separated by too many linebreaks, tables are weirdly placed etc).

I've tried upgrading and downgrading versions although other problems occured (like unicode support for fonts etc)

Any ideas ?

My requirements
```bash
Babel==1.3
Chameleon==2.20
GeoAlchemy2==0.2.4
Jinja2==2.7.3
Mako==1.0.1
MarkupSafe==0.23
PasteDeploy==1.5.2
*Pillow==2.7.0*
Pygments==2.0.2
SQLAlchemy==0.9.8
WTForms==2.0.2
WebOb==1.4
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.3.2
bpython==0.13.2
certifi==14.05.14
click==3.3
cornice==0.17
coverage==3.7.1
itsdangerous==0.24
lingua==3.8
nose==1.3.4
passlib==1.6.2
polib==1.0.6
psycopg2==2.5.4
pyramid==1.5.2
pyramid-debugtoolbar==2.3
pyramid-debugtoolbar-ajax==0.0.4
pyramid-jinja2==2.3.3
pyramid-mailer==0.14
pyramid-mako==1.0.2
pyramid-redis-sessions==1.0a2
pyramid-tm==0.10
pytz==2014.10
raven==5.1.1
redis==2.9.1
*reportlab==2.5*
repoze.lru==0.6
repoze.sendmail==4.2
requests==2.5.1
rq==0.5.0
simplejson==3.6.5
six==1.9.0
sockjs-tornado==1.0.1
suds==0.4
tornado==4.0.2
transaction==1.4.3
translationstring==1.3
venusian==1.0
*xhtml2pdf==0.0.5*
zope.deprecation==4.1.2
zope.interface==4.1.2
zope.sqlalchemy==0.7.5
Sphinx==1.2.3
waitress==0.8.9
rq-scheduler==0.5.0
hiredis==0.1.5
gunicorn==19.2.0
````

**Comment by chrisglass** [comment]
This project is largely unmaintained unfortunately. I picked it up because I wanted to merge some stuff and nobody was around to do it - but nobody is around to answer questions or program anymore.

So if it really itches, I suggest you hire somebody to work on this (or some other) project and do it for you.

Sorry, and thanks for your understanding.

**Comment by halfnibble** [comment]
@chrisglass this seems like it would be an essential part of many projects. Is there a competing library?

@ghandee Are you saying this happens exactly at the 50th mark? Or was that a generalization for "after multiple renders"? Also, once it starts generating poorly, does it continue, or randomly go back to good renders?

**Comment by chrisglass** [comment]
@halfnibble people usually agree with you, but so far I've yet to see sombody agree to the point where they commit ressources to actually develop and maintain that "essential part of many projects".

Patches welcome. I stepped up years ago to merge my own patches, don't let that prevent you from stepping up as well :)

**Comment by chrisglass** [comment]
(oh and I should add, if somebody wants commit rights, I'm more than happy to give them)

**Comment by ghandee** [comment]
@halfnibble: it happens randomly, what I meant is its' quite hard to reproduce

I supposte this may be caused by some version mistmatch - this package uses internally reportlab which uses pillow etc

@chrisglass 
Sorry to hear that, i'll be probably moving to some different tool then

**Comment by xj9** [comment]
We have an active fork at [zulumarketing/html2pdf][1]; would you mind opening an issue over there too?

We haven't made any releases yet, but we have made a lot of progress modernizing the codebase (in particular, we've managed to get it working on Py3k), and we would love to hear what broken bits the community would like to help us fix, and what y'all would like to see *us* fix.

I've opened an [issue][2] specifically to discuss where this library needs to change and what the roadmap will look like.

[1]: https://github.com/zulumarketing/html2pdf
[2]: https://github.com/zulumarketing/html2pdf/issues/4

**Comment by chrisglass** [comment]
Oh ! That's great news!

I'd be happy to give you guys you upload rights, and bless your fork as the
official one, add I unfortunately have no tone to spend on this project
anymore (not that I was a particularly active maintainer at any point).

Let me know if that would help

Chris

**Comment by xj9** [comment]
Sounds great!

**Comment by benjaoming** [comment]
The original issue doesn't sound nice, but because of the overflow of largely old issues that are hard to compare to the current `develop` branch, I'm gonna close it and please do scream if you want it reopened.
