### ISSUE TITLE
Project Ownership

### ISSUE THREAD

**Issue by tokyo-jesus** [xhtml2pdf/xhtml2pdf#228]
You mentioned in the README that you would be interested in transferring ownership to someone who is interested in maintaining the project. The company I work for ([Zulu Marketing][1]) uses this package internally in mission-critical software.

If you don't mind we'd like to take over management/ownership.

[1]: https://github.com/zulumarketing

**Comment by dmr** [comment]
Version 0.0.6 is over a year old, is this project still alive?
In master there is some python3 support. Can anyone release this as a new version?

**Comment by benjaoming** [comment]
@dmr -- have a look at the commit history. Yeah it's absolutely alive. I've opted to maintain it. If you wanna help make the Python 3 release happen, I would suggest heading over to #222 - this effort really needs more collaboration, and especially the project as a whole could do with more test coverage. I'm totally gonna cheer on this effort, however I'm trying to maintain a role of just maintaining and not dev'ing.

The main problems with the Python 3 support has been that a lot of people did separate PRs on it and it didn't really work, also test coverage was very low. However, now that we have those things in place (coverage metrics), I'd say there's a good chance we can go somewhere.

**Comment by dmr** [comment]
Thank you for the quick response, but I think I'm not going to use xhtml2pdf for the project I was working on yesterday.
I needed to solve the python3 as a package issue yesterday and I ended up using subprocess with "wkhtmltopdf" which works fine for me.

**Comment by benjaoming** [comment]
sounds good, that's a nice project, quite a different scope though.
