### ISSUE TITLE
Internal link menu

### ISSUE THREAD

**Issue by CARocha** [xhtml2pdf/xhtml2pdf#229]
Hi all, o try use internal link for navigation menu in pdf, but
not working only paint blue color the link but when i clic not happen nothing :/ :(
i try this:
<a href="#hello">link</a>

and them
<a name="hello">here</a>

but the link not working only in html :/ 
any tips or tricks

i user this in my enviroments:
reportlab==2.6
pisa==3.0.33
pyPdf==1.13
html5lib==0.999
Django==1.7.7

the pdf working html to pdf but only the link menu navigation not working :/ :(

**Comment by karthip26** [comment]
Hi all, Is there any tricks to make internal links working. Kindly help me on the issue, i am struck .
