### ISSUE TITLE
Font CSS Generates AttributeError

### ISSUE THREAD

**Issue by Xangis** [xhtml2pdf/xhtml2pdf#232]
When processing font tags from CSS, this AttributeError is generated:

'list' object has no attribute 'encode'

I suspect it expects a single URL rather than multiple. Here's where and how the error occurs from the Django stack trace:

![xhtml2pdf_font_error](https://cloud.githubusercontent.com/assets/931548/7443906/a348fc6a-f120-11e4-8628-77bf087ac773.png)

Possibly related to #151 and #195.

**Comment by xj9** [comment]
We have an active fork at [zulumarketing/html2pdf][1]; would you mind opening an issue over there too?

We haven't made any releases yet, but we have made a lot of progress modernizing the codebase (in particular, we've managed to get it working on Py3k), and we would love to hear what broken bits the community would like to help us fix, and what y'all would like to see *us* fix.

I've opened an [issue][2] specifically to discuss where this library needs to change and what the roadmap will look like.

[1]: https://github.com/zulumarketing/html2pdf
[2]: https://github.com/zulumarketing/html2pdf/issues/4

**Comment by benjaoming** [comment]
Okay, hope I'm not rocking the boat too much... but I've merged #199 and suspect this to be fixed now!
