### ISSUE TITLE
Tags for PyPI releases?

### ISSUE THREAD

**Issue by xaibeha** [xhtml2pdf/xhtml2pdf#234]
Last tag is 0.0.4 from 2012; current PyPI release is 0.0.6 from a month ago (2015-04-27).

Could you restart tagging releases, including 0.0.5 and 0.0.6 retroactively? It would make comparing states against source a bit easier.

**Comment by xj9** [comment]
We have an active fork at [zulumarketing/html2pdf][1]; would you mind opening an issue over there too?

We haven't made any releases yet, but we have made a lot of progress modernizing the codebase (in particular, we've managed to get it working on Py3k), and we would love to hear what broken bits the community would like to help us fix, and what y'all would like to see *us* fix.

I've opened an [issue][2] specifically to discuss where this library needs to change and what the roadmap will look like.

[1]: https://github.com/zulumarketing/html2pdf
[2]: https://github.com/zulumarketing/html2pdf/issues/4

**Comment by dmr** [comment]
@tokyo-jesus Are there any plans to merge the fork?

**Comment by benjaoming** [comment]
This has been investigated and tags have been added: https://github.com/xhtml2pdf/xhtml2pdf/releases
