### ISSUE TITLE
Python 2.7 Django not working

### ISSUE THREAD

**Issue by nikolaz111** [xhtml2pdf/xhtml2pdf#242]
I keep getting a TypeError exception:
```
unicode argument expected, got 'str'
```
When I try to do this:
```python
data = {'data': somedata}

    template = get_template('sometemplate.html')
    html = template.render(Context(data))
    result = StringIO()

    status = pisa.CreatePDF(StringIO(html), result)
```
I saw the Django example and the code is similir to this one. Any clues?

Thank you

**Comment by teeberg** [comment]
Could you post the full stack trace for that error message?

**Comment by ccemeraldeyes** [comment]
+1 on this

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  57.         return view_func(*args, **kwargs)
File "/path/to/our/views.py" in thing_print
  404.         pdf = pisa.CreatePDF(html, result)
File "/usr/local/lib/python2.7/dist-packages/xhtml2pdf/document.py" in pisaDocument
  172.     context.dest.write(data)  # TODO: context.dest is a tempfile as well...

Exception Type: TypeError at /thing-print
Exception Value: unicode argument expected, got 'str'

**Comment by benjaoming** [comment]
Please try the latest pre-release, `pip install xhtml2pdf --pre --upgrade`

**Comment by juosvidi** [comment]
The latest pre-release doesn't work.

**Comment by benjaoming** [comment]
Closing this until someone gives useful input. Also, I don't see this problem, so I suspect you're feeding non-unicode data to `CreatePDF` as the error hints.
