### ISSUE TITLE
Unicode font fallback not working

### ISSUE THREAD

**Issue by teeberg** [xhtml2pdf/xhtml2pdf#244]
When generating a PDF, I have some characters that render fine using "Helvetica" (characters like `ǹ`, `Ț`, `ȑ`) but also others that don't. These others (e.g. Chinese characters) seem to work fine when I use "Arial Unicode", but Arial Unicode does not support either of `ǹ` or `Ț`. So I figured I could specify several font families, just like in a browser, where it would go through the list to find a font family that has the missing glyphs:
```css
body {
    font-family: "Arial Unicode", "Helvetica", "sans-serif";
}
```
But that is the same as if I only specified "Arial Unicode". If I reverse the order, it's the same as if I only specified "Helvetica". So it seems to me that xhtml2pdf only ever looks at the first font in the list, even though, according to the debug log, it loads all specified font files.

**Comment by benjaoming** [comment]
I think this is a matter of the lower layers, reportlab and also ultimately the responsibility of the PDF viewer. xhtml2pdf won't be able to parse font files (that may not even be present on the server) to analyze which glyphs are there and which are in the displayed elements etc.
