### ISSUE TITLE
How can I set PDF meta-data

### ISSUE THREAD

**Issue by ZuluPro** [xhtml2pdf/xhtml2pdf#251]

**Comment by alistair-broomhead** [comment]
There's currently no way, but I just opened a PR to do the same: #257

**Comment by benjaoming** [comment]
So as @alistair-broomhead 's #259 is now merged into 'develop', you can start using the new feature :) Works like this:

```python
pisaDocument(
    src=six.StringIO(HTML_CONTENT),
    dest=pdf_file,
    context_meta=METADATA
)
```
