### ISSUE TITLE
Missing tags for 0.0.5 and 0.0.6 releases

### ISSUE THREAD

**Issue by mgedmin** [xhtml2pdf/xhtml2pdf#255]
If you check https://github.com/xhtml2pdf/xhtml2pdf/tags, you'll find that there are no tags corresponding to 0.0.5 and 0.0.6 PyPI releases.

Could you `git push --tags` from whatever local repository you used to make those releases?

**Comment by benjaoming** [comment]
Sorry, this was a missing practice of the previous maintainers. If you can research which commits correspond to those releases, we could add tags.

**Comment by mgedmin** [comment]
It looks like 0.0.5 was made from commit 116fede80d8ae91f0c2f458f2ab2ba829bdff331, and 0.0.6 was made from commit 7b978bd526e833815e0ddf0f9817011b19fb7c42.

I found these commits by doing `git log -S 0.0.5`, and then verified by checking them out, running `python setup.py sdist`, and comparing the tarball with the one downloaded from PyPI using [diffoscope](https://pypi.python.org/pypi/diffoscope): the only differences were file timestamps, owner/group names in the tarball, and a trailing newline in requires.txt (probably caused by me using a different setuptools version).

**Comment by benjaoming** [comment]
Cool, I've added them as releases now. Thanks for investigating and opening up the issue!

https://github.com/xhtml2pdf/xhtml2pdf/releases

**Comment by mgedmin** [comment]
Thank you!
