### ISSUE TITLE
Website http://www.xhtml2pdf.com is not working

### ISSUE THREAD

**Issue by vstoykov** [xhtml2pdf/xhtml2pdf#262]
There is problem with DNS.

**Comment by benjaoming** [comment]
Thanks for reporting!

Seems like it's done for, let's not be sad though, there was nothing there really significant. You can still see it here:

https://web.archive.org/web/20150915080438/http://xhtml2pdf.com/

**Comment by benjaoming** [comment]
Btw. it's the former maintainer who has left that had control of the domain.
