### ISSUE TITLE
CHANGELOG.txt not updated for 0.0.6 or 0.1a1

### ISSUE THREAD

**Issue by ddamoursNRC** [xhtml2pdf/xhtml2pdf#274]
The CHANGELOG.txt file seems to be stale.
If recent changes are being tracked elsewhere a pointer should be added to the changelog, otherwise it should be updated with recent features / bugfixes.

**Comment by benjaoming** [comment]
That PR would be awesome! I'm afraid that only issues, PRs, and commit histories can help us. I gave up before the 0.1a1 because it seemed like yet another delay postponing a final release.

**Comment by benjaoming** [comment]
Some updates added
