### ISSUE TITLE
Error Unicode AscII (in pdf)

### ISSUE THREAD

**Issue by PKpacheco** [xhtml2pdf/xhtml2pdf#275]
I'm using xhtml2pdf to render html to pdf but even with the Html with uft-8, the PDF are with Unicode AscII error. I tried overwriting the source template in my putting some other and the error persists.
Some source or configuration option so that I can generate PDF without errors?

**Comment by emilkjer** [comment]
Hi Paola

Can you please copy/paste the stack trace of the error?

/Emil

**Comment by PKpacheco** [comment]
then I could generate the PDF putting a font in the css. But it generates full of errors in UTF-8
are those black squares on the accent places.

**Comment by emilkjer** [comment]
Can you link to a code example?

**Comment by PKpacheco** [comment]
So, I decided changed font, overide for other font ( arial unicode) and ok!!!

thank you very much .. I thought it was to redo all the functionality with another library
