### ISSUE TITLE
Problem no module named xhmtl2pdf

### ISSUE THREAD

**Issue by rafaellg8** [xhtml2pdf/xhtml2pdf#276]
The library works on local fine, but when I try to deploy on Google App Engine show me

from xhtml2pdf import pisa
ImportError: No module named xhtml2pdf

I installed the xhtml2pdf by pip but the error persists.

Thanks.

**Comment by thongnv** [comment]
please note that xhtml2pdf does not support python3

**Comment by benjaoming** [comment]
The only way to get _somethings_ working is to install the dev release which needs community help to be finalized:  `pip install xhtml2pdf --pre`
