### ISSUE TITLE
Open pdf files in new tab

### ISSUE THREAD

**Issue by RasmusFriis** [xhtml2pdf/xhtml2pdf#277]
Does anyone know, how to make the pdf files open in new tab ?
I cant find any methods in the Htmlresponse, which will render a new page.

**Comment by RasmusFriis** [comment]
Hei Emil.
Thank you very much, this is working now.

**Comment by benjaoming** [comment]
Thanks @emilkjer for explaining :) Going to close this issue, since it doesn't seem to relate to the xhtml2pdf code.

I wish we had RTD so we could collect a section with recipes. Oh well.

**Comment by RasmusFriis** [comment]
Thank you all of you, sorry I havent closed the question.

2016-04-19 11:44 GMT+02:00 Benjamin Bach <notifications@github.com>:

> Thanks @emilkjer <https://github.com/emilkjer> for explaining :) Going to
> close this issue, since it doesn't seem to relate to the xhtml2pdf code.
>
> I wish we had RTD so we could collect a section with recipes. Oh well.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xhtml2pdf/xhtml2pdf/issues/277#issuecomment-211828940>
>



-- 
De bedste hilsener / Best Regards
Rasmus Friis

Ved Bellahøj Syd 23B
2700 Brønshøj
Phone: +45 31152585
