### ISSUE TITLE
Python 3: Bad table formatting with empty columns

### ISSUE THREAD

**Issue by citizen-stig** [xhtml2pdf/xhtml2pdf#279]
Content of the columns are overlapped if there's an empty cells.

Here is code for reproducing:
```
# -*- encoding: utf-8 -*-
from xhtml2pdf import pisa
import sys

py_version = '{0}.{1}'.format(sys.version_info[0], sys.version_info[1])
outputFilename = "bad_table_" + py_version + ".pdf"
source_html = '<html><body>' \
              '<table>' \
              '<tr>' \
              '<td>Item</td><td>Value 1</td><td>Value2</td><td>Value3</td>' \
              '</tr>' \
              '<tr>' \
              '<td>Item 1</td><td>11</td><td>12</td><td>13</td>' \
              '</tr>' \
              '<tr>' \
              '<td>Item 2</td><td>21</td><td>22</td><td>23</td>' \
              '</tr>' \
              '<tr>' \
              '<td>Item 3</td><td>31</td><td>32</td><td>33</td>' \
              '</tr>' \
              '<tr>' \
              '<td>TOTAL</td><td></td><td></td><td>100</td>' \
              '</tr>' \
              '</table>' \
              '</body></html>'

if __name__ == "__main__":
    result_file = open(outputFilename, "w+b")
    pisa_status = pisa.CreatePDF(
        source_html,
        dest=result_file)
    result_file.close()
    print(pisa_status)
```

And this is how results are compared.
![badtables](https://cloud.githubusercontent.com/assets/3115300/14082553/501c3996-f519-11e5-9f48-0f8db9002a63.png)

I've used a latest version from develop branch 1.a1

**Comment by citizen-stig** [comment]
I've found a quick workaround, use a space in ```<td> </td>``` instead of ```<td></td>```

**Comment by benjaoming** [comment]
@citizen-stig so I take it that the difference in behavior is between Python 2 and Python 3 using the same version, right?

Would you be able to work on a resolution?

**Comment by citizen-stig** [comment]
Yes, the problem appears only in Python3. I've described workaround and I'll try to propose a fix for that

**Comment by benjaoming** [comment]
Thanks! Would be happy to merge and release a fix!

**Comment by benjaoming** [comment]
There, should be fixed now, please have a look @citizen-stig and feel free to investigate further into this matter if the solution is sufficient.. `xhtml2pdf.tables` is a shady module.

**Comment by arkadicolson** [comment]
I see this problem also in python2.7? Is it possible to fix it in that version to?

**Comment by LegoStormtroopr** [comment]
@arkadicolson The code for Python 2 and 3 is the same, can you state which version of XHTML2PDF you are on, and an example input and output?
