### ISSUE TITLE
Python3 fix Image Render in PDF

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [xhtml2pdf/xhtml2pdf#282]
Hi,

I don't know to make a pull request so I will just post the solution here.

In case you are using python3 and you are trying to render an image on the PDF

Change these lines:

/xhtml2pdf/xhtml2pdf_reportlab.py line 35:** from io import StringIO, BytesIO**
/xhtml2pdf/xhtml2pdf_reportlab.py line 514: **img = PmlImageReader(BytesIO(self._imgdata))**

/xhtml2pdf/document.py **remove line 184 and 185**

**Comment by benjaoming** [comment]
@Dean-Christian-Armada thanks for the report, however I do not recognize these lines. They have all been fixed in the latest pre-release and in the master branch. Try out these, and feel welcome to do PR in case you run into further Python 3 issues.
