### ISSUE TITLE
int() argument must be a string or a number, not 'tuple'

### ISSUE THREAD

**Issue by freetest** [xhtml2pdf/xhtml2pdf#286]
Hi， i use the deom  show me error

python 2.7

django 1.8.6

![1](https://cloud.githubusercontent.com/assets/5380255/14662068/6c66da60-06e5-11e6-8ecf-88c5e56a3805.png)

![2](https://cloud.githubusercontent.com/assets/5380255/14662076/7f68acec-06e5-11e6-8043-6ab1f7c8ad3c.png)

**Comment by benjaoming** [comment]
Dear @freetest,

Please do not post screen shots, post the full traceback. The above does not even show the full traceback, so it's impossible to tell what when wrong.

Click "Switch to copy-and-paste view", then grab the output there.

**Comment by benjaoming** [comment]
Impossible to work out, not enough info.
