### ISSUE TITLE
Make everything sortable in w3c.css

### ISSUE THREAD

**Issue by benjaoming** [xhtml2pdf/xhtml2pdf#299]
In relation to #69, we need to introduce ordering for Python 3, since things fail loudly when sorting is done on objects that do not support it.

The current implementation is insufficient since it supposes that `type(A) == type(B)` when sorting stuff.. which is probably not how it works.

Solving this issue should either be done by dirty implementation or a refactor of the classes and inheritance in w3c.css which needs a loving hand as well... possibly introducing a real CSS parser even, like `tinycss`.

**Comment by fbernhart** [comment]
Since Python 3.6 dicts are always insertion-ordered; And as we'll be dropping support for Python < 3.6 very soon, the problem described in #69 shouldn't be an issue anymore.

So maybe we could close this?
