### ISSUE TITLE
Example from docs produces an empty PDF

### ISSUE THREAD

**Issue by citizen-stig** [xhtml2pdf/xhtml2pdf#300]
I've tried to run example from documentation and it produces empty PDF file on python2.7 and latest develop branch.

I've also noticed, that in python2.7 file has header PDF-1.3 and on python3.5 PDF-1.4. 

I believe it should generate PDF files of same versions across python versions

**Comment by benjaoming** [comment]
Could you dump the example code that you tried here together with the code snippet that generated the empty pdf?

**Comment by citizen-stig** [comment]
I use example from https://github.com/xhtml2pdf/xhtml2pdf/blob/master/doc/usage.rst:

    # -*- encoding: utf-8 -*-
    from xhtml2pdf import pisa             # import python module
    
    # Define your data
    sourceHtml = "<html><body><p>To PDF or not to PDF</p></body></html>"
    outputFilename = "test.pdf"
    
    # Utility function
    def convertHtmlToPdf(sourceHtml, outputFilename):
        # open output file for writing (truncated binary)
        resultFile = open(outputFilename, "w+b")
    
        # convert HTML to PDF
        pisaStatus = pisa.CreatePDF(
                sourceHtml,                # the HTML to convert
                dest=resultFile)           # file handle to receive result
    
        # close output file
        resultFile.close()                 # close output file
    
        # return True on success and False on errors
        return pisaStatus.err
    
    # Main program
    if __name__ == "__main__":
        pisa.showLogging()
        convertHtmlToPdf(sourceHtml, outputFilename)

I've tried to debug and found a key differences between ```context``` object in py2.7 and p3.5:

Attribute ```story```:
2.7: [Spacer(1, 1)]
3.5: [PmlParagraph(...)]

Attribute ```text```:
2.7: To PDF or not to PDF
3.5:

**Comment by benjaoming** [comment]
Python 3.4: Works
Python 2.7: Blank :(

**Comment by citizen-stig** [comment]
I think I've found a problem, please take a look: https://github.com/xhtml2pdf/xhtml2pdf/pull/301

**Comment by benjaoming** [comment]
Thanks for fixing this!
