### ISSUE TITLE
Cannot explicitly set an encoding with a unicode string

### ISSUE THREAD

**Issue by freetest** [xhtml2pdf/xhtml2pdf#304]
i use Using xhtml2pdf in Django code

    # Write PDF to file
    f = open('test2.pdf',"w+b")
    pisaStatus = pisa.CreatePDF(html, dest=f, link_callback=link_callback,encoding='utf-8')

TypeError at /html2/
Cannot explicitly set an encoding with a unicode string
Request Method:	GET
Request URL:	http://127.0.0.1:8000/html2/
Django Version:	1.8.6
Exception Type:	TypeError
Exception Value:	
Cannot explicitly set an encoding with a unicode string
Exception Location:	/Users/wx/pythonenv/django1.8/lib/python2.7/site-packages/html5lib/inputstream.py in HTMLInputStream, line 144
Python Executable:	/Users/wx/pythonenv/django1.8/bin/python
Python Version:	2.7.10

**Comment by freetest** [comment]
if not use encoding='utf-8'  the pdf 
![ok](https://cloud.githubusercontent.com/assets/5380255/15091545/972e6df2-147e-11e6-9d3f-09f21c8d2338.png)

**Comment by benjaoming** [comment]
Duplicate of #11
