### ISSUE TITLE
Encoding a BytesIO object failing in Python 3

### ISSUE THREAD

**Issue by blaise-io** [xhtml2pdf/xhtml2pdf#306]
https://github.com/xhtml2pdf/xhtml2pdf/blob/master/xhtml2pdf/document.py#L181

This does not work. The BytesIO object does not allow calling encode().

(Not an issue in 0.1a2 where this if statement is not added yet: https://github.com/xhtml2pdf/xhtml2pdf/blob/0.1a2/xhtml2pdf/document.py#L181. Also, I noticed this was removed in 0.1a3 anyway: https://github.com/xhtml2pdf/xhtml2pdf/pull/269/files#diff-0521bac2cf0a435397f93b2ed2d6e363L181)

**Comment by benjaoming** [comment]
Hi @blaise-io 

You are referring to the `master` branch which isn't under active dev. However, the `develop` branch is.

I'm wondering what you mean exactly? That 0.1a2 is broken but it's fixed in 0.1a3? Because then we can go ahead and close this issue, also :)

**Comment by blaise-io** [comment]
Yeah, if master is not under dev, this isn't an issue :)
