### ISSUE TITLE
Now broken with html5lib

### ISSUE THREAD

**Issue by LegoStormtroopr** [xhtml2pdf/xhtml2pdf#318]
From https://pypi.python.org/pypi/html5lib/0.99999999:

> Move a whole load of stuff (inputstream, ihatexml, trie, tokenizer, utils) to be underscore prefixed to clarify their status as private

Except https://github.com/xhtml2pdf/xhtml2pdf/blob/master/xhtml2pdf/parser.py#L17:

> ```
> from html5lib import treebuilders, inputstream
> ```

Current fix:
-     Use `pip install html5lib==1.0b8`

**Comment by davidthornton** [comment]
You beat me by seven minutes

**Comment by karimone** [comment]
Thanks. Really thanks

**Comment by patroqueeet** [comment]
+1

**Comment by alexandre** [comment]
Why not open a pull request and fix it in the requirements.txt ? We should do it, shouldn't we ?

**Comment by LegoStormtroopr** [comment]
@alexandre Done. See #319

**Comment by benjaoming** [comment]
The PR that fixes this can be merged once tests pass. After that, I can upload a fix.

**Comment by alexandre** [comment]
@benjaoming ,

Great! and thank you, @LegoStormtroopr . =]

**Comment by benjaoming** [comment]
Fixed and released as 0.1b2

**Comment by LegoStormtroopr** [comment]
Thanks @benjaoming

**Comment by VSPPedro** [comment]
+ 1

**Comment by VSPPedro** [comment]
+ 1

**Comment by benjaoming** [comment]
@VSPPedro what do you mean exactly? The issue is closed and a fix has been merged.

**Comment by VSPPedro** [comment]
This post helped me. Sorry, i was just trying to say thank you. Don't get me wrong.

+1  == + 1 like. That was my thought. haha

Thank you.

**Comment by danielquinn** [comment]
It appears that this change hasn't made it into PyPi yet.  If I do `pip install xhtml2pdf`, this is what's installed:

    Successfully installed Pillow-3.4.2 html5lib-0.999999999 pyPdf2-1.26.0 reportlab-3.3.0 six-1.10.0 webencodings-0.5 xhtml2pdf-0.0.6

**Comment by benjaoming** [comment]
@danielquinn - of course it's on PyPi :) Please use the `--pre` switch for `pip` as it won't automatically install beta versions.

**Comment by LegoStormtroopr** [comment]
@benjaoming I'm going to reopen this bug, so I can track its status. I'll try and do some fixes to upgrade to the latest version of htmllib5.

**Comment by LegoStormtroopr** [comment]
Guess what! We have html5lib==1.b10 support! And Python 3 too - #332

**Comment by alexkiburu** [comment]
Awesome! and thank you, @LegoStormtroop

**Comment by HuHaichun** [comment]
You awesome. Fix my issue
