### ISSUE TITLE
error Multiple definitions in dictionary  for key /Type

### ISSUE THREAD

**Issue by radzhome** [xhtml2pdf/xhtml2pdf#333]
I get this if the pdf has multiple /Type definitions:

`[<xhtml2pdf.util.pisaTempFile object at 0x4ef16d0>], error Multiple definitions in dictionary at byte 0x4731f for key /Type` 

```
base_pdf = pisaPDF()

for file in order_data['files']:
    file_content = ...
    base_pdf.addFromString(file_content)
    output_file_buffer = base_pdf.getvalue()
```

Any easy way to avoid this?

**Comment by radzhome** [comment]
To fix, I replaced line 52 of `xhtml2pdf/pdf.py` from:

`input = PyPDF2.PdfFileReader(pdffile)`

to 

`input = PyPDF2.PdfFileReader(pdffile, strict=False)`

**Comment by LegoStormtroopr** [comment]
Thanks for this, looks like you've already identified the issue which is great!

Can you include some sample code that caused the bug so we can improve the testing?

**Comment by ppmm** [comment]
@radzhome  however, through this way, the code can excute, but the pdf file merged can not be used
