### ISSUE TITLE
fails on 'Printing a book with css' code.

### ISSUE THREAD

**Issue by illume** [xhtml2pdf/xhtml2pdf#34]
Hi,

there is an article here on using css+html to print a book.
    http://www.alistapart.com/articles/boom

It may be a good test case, since it deals with a fairly common layout.

Here are the files from the article.

curl -O http://people.opera.com/howcome/2005/ala/sample.html
curl -O http://people.opera.com/howcome/2005/ala/sample.css
curl -O http://people.opera.com/howcome/2005/ala/sample.pdf

$ xhtml2pdf sample.html xhtml2pdf_sample.pdf

Here is the error:

  File "/Users/rene/xhtml2pdfenv/lib/python2.7/site-packages/xhtml2pdf-0.0.3-py2.7.egg/xhtml2pdf/w3c/cssParser.py", line 664, in _parseAtPage
    stylesheetElements.extend(atResults)
TypeError: 'NotImplementedType' object is not iterable

**Comment by benjaoming** [comment]
FYI this works in the latest `develop` branch. Thanks for the sample reference.
