### ISSUE TITLE
The current version is 0.2b, but no corresponding release tag / changelog entry

### ISSUE THREAD

**Issue by vartec** [xhtml2pdf/xhtml2pdf#342]
The latest release tag `0.1b2`, 
latest CHANGELOG.txt entry is `0.1alpha4`
latest version is `0.2b`

**Comment by LegoStormtroopr** [comment]
I've added a new release and will update the Changelog on the next release, thanks!

**Comment by barseghyanartur** [comment]
@LegoStormtroopr:

Perfect! Thanks. :)
