### ISSUE TITLE
Problems with some Unicode characters

### ISSUE THREAD

**Issue by metakermit** [xhtml2pdf/xhtml2pdf#345]
Hi, I'm using the latest xhtml2pdf (0.2b1) & reportlab (3.4.0) through django-easy-pdf (0.1.0) on Python 3.6.0 and it's working great for the most part! One problem I am still experiencing, though, is that some Unicode characters are not rendering properly (šŠčČćĆđĐžŽ):

![screen shot 2017-03-29 at 16 38 36](https://cloud.githubusercontent.com/assets/1818628/24460321/430c975a-149e-11e7-9692-0f33245afce3.png)

I'm using the default [django-easy-pdf base template](https://github.com/nigma/django-easy-pdf/blob/master/easy_pdf/templates/easy_pdf/base.html) and I found that I can somewhat repair things if I override it to declare the html encoding:

````
{% block extra_style %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
{% endblock %}
````
Which results in some characters being rendered correctly like Š and Ž, but not all of them (Č, Ć, Đ are still blacked out).

![screen shot 2017-03-29 at 16 38 19](https://cloud.githubusercontent.com/assets/1818628/24460308/39c23a9c-149e-11e7-8620-002b5f957fd3.png)

I tried experimenting with different font declarations (sans-serif, serif, external fonts), but I can't seem to fix this. The characters are never rendered correctly. I don't know if I'm missing some xhtml2pdf / Reportlab setting here. Do you maybe have an idea of a possible solution?

**Comment by pacotole** [comment]
I have de same issue after update xhtml2pdf to v.0.2b1 and I fix the problem adding `<meta charset="UTF-8">` to html templates.

**Comment by BobBowles** [comment]
I am having the same problem using `django-easy-pdf==0.1.0` and `xhtml2pdf==0.2b1`, with display of Chinese and accented Roman characters. It does not seem to matter which font I use, I have tried several, including ones specifically designed for Chinese. All I end up with for the non-ascii characters is tofu. It looks like the fonts are not being embedded correctly. While declaring the charset encoding with a meta declaration is necessary, it is not sufficient.

**Comment by jb-lee** [comment]
I ran into this issue, too. 
Sadly, those Korean characters were just printed as black boxes.
ex) "안녕하세요" <- it means "hello"
![error](https://cloud.githubusercontent.com/assets/19926817/26298252/8bfa1620-3f11-11e7-96cb-9ccdb705d591.png)

**Comment by m7allaq** [comment]
same problem ")

**Comment by xinshangshangxin** [comment]
change fonts may work
```html
<meta http-equiv=Content-Type content="text/html;charset=utf-8">
@font-face {
  font-family: Microsoft Yahei Mono;
  src: url("download the YaHei Mono.ttf");
}

* {
  font-family: Microsoft Yahei Mono
}
```

the `Microsoft Yahei Mono` from
https://github.com/Microsoft/WSL/issues/2463#issuecomment-334692823

**Comment by adrian-chrostowski** [comment]
Any news on fixing the bug? I tried all of the solutions I found on the web and none work, I still get nasty boxes instead of non-latin characters.

**Comment by SimonAstani** [comment]
> I ran into this issue, too.
> Sadly, those Korean characters were just printed as black boxes.
> ex) "안녕하세요" <- it means "hello"
> ![error](https://cloud.githubusercontent.com/assets/19926817/26298252/8bfa1620-3f11-11e7-96cb-9ccdb705d591.png)

Did you find any solution..

**Comment by bassem79** [comment]
Hello, i have the same problem with arabic characters
any solution ??

**Comment by bassem79** [comment]
up
please solution for arabic characters using xhtml2pdf and pisa

**Comment by kooshan75** [comment]
I'm having the same problem guys...

**Comment by alispa** [comment]
Me too. Slaven characters, 3 of 5 work, the other 2 do not work. Changing fonts makes me even bigger problems.

**Comment by stasharrofi** [comment]
I have the same issue with Arabic characters.

**Comment by kasarda** [comment]
I got this problem thousands of times. There are a few things you should try:

1. Make sure you have
   ```
   ```

**Comment by kasarda** [comment]
I got this problem thousands of times. 
There are a couple of things you might do:

1. Use encoding metadata in the template
    ```html
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="UTF-8">
     ```
2. Try to set encoding in CreatePDF method (metadata in the template should do the work but you can try this, you never know what happens)
   ```python
     pisa.CreatePDF(
        template, dest=response, link_callback=link_callback, encoding='UTF-8')
     ```
3. Change your font (This will solve this issue almost every time)
      But remember that some fonts even if they are supporting some special characters they just don't work so you have to try many of them(Sometimes I even tried like 20 fonts 'till I solved this issue so don't give up :)). The font that never disappoints me is Roboto from Google. This is like the king of fonts because it looks good and it just works for me every time :D. Try to download .ttf file of any font and then apply this font like this (I never tested other formats except for .ttf so maybe other formats will work as well):
```css
        @font-face {
            font-family: Roboto;
            src: url(static/fonts/Roboto-Regular.ttf);
        }

        @font-face {
            font-family: Roboto;
            src: url(static/fonts/Roboto-Bold.ttf);
            font-weight: bold;
        }
```
Don't forget to use this font:
```css
 body {
     font-family: "Roboto", sans-serif;
  }
```
https://xhtml2pdf.readthedocs.io/en/latest/reference.html#fonts
If this will not work for you then make sure your path to the .ttf file is correct (Try for example add to the "fonts" folder some image and render the image to the pdf so you make sure you have the static path set up correctly) and check if step 1. and 2. are applied otherwise .. well God help you.
4. Try different library

**Comment by Da2software** [comment]
in my case, it was the font problem, I did this to make it works.
 @font-face {
            font-family: Roboto;
            src: "file://YOUR_ABSOLUTE_PATH_FILE_HERE";
 }
I used an absolute path and also the "file://", I'm not sure why the other methods didn't work for me.

**Comment by hadriankubasiewicz** [comment]
In my case helps

<style>
      @font-face {
        font-family: Roboto;
        src: "C://Users//user//Desktop//Project//static//fonts//Roboto-Regular.ttf";
      }
      body {
        font-family: "Roboto", sans-serif;
</style>

**Comment by kasarda** [comment]
> In my case helps
> 
> <style> @font-face { font-family: Roboto; src: "C://Users//user//Desktop//Project//static//fonts//Roboto-Regular.ttf"; } body { font-family: "Roboto", sans-serif; </style>

It is always a bad idea to use an absolute path to resources since your application is not going to run on your machine in production or other developers can have different paths. You need some relative path like "/static" otherwise you are going to have some serious trouble in the future. Do you have a relative path for this HTML template working and only fonts aren't working or you can't set up a relative path for the template? You can try to put some image to a static folder and then you can add <img/> tag in PDF so you can tell if your relative path is set up correctly if the image is displayed.

**Comment by phnx** [comment]
I was trying absolute path as many people recommended. Neither of the solutions work.
So I checked Django terminal and found following error message caught by xhtml2pdf;

`django.core.exceptions.SuspiciousFileOperation: The joined path (absolute/path/to/Tahoma.ttf) is located outside of the base path component (my/static/path)`

while inside my link_callback method is like;
`sUrl = settings.STATIC_URL  # Typically /static/
        sRoot = settings.STATIC_ROOT  # Typically /home/userX/project_static/
        mUrl = settings.MEDIA_URL  # Typically /media/
        mRoot = settings.MEDIA_ROOT  # Typically /home/userX/project_static/media/`

It seems that xhtml2pdf wouldn't just look up file from absolute path (/Users/.../static/font/Tahoma.ttd). 
Instead, it uses relative path to the static folder set in link_callback.
So in my case font-face became;

` @font-face {
            font-family: Tahoma;
            src: "font/Tahoma.ttf";
        }
`

Not sure if this would work for you guys as well.

**Comment by pedroszg** [comment]
Hi!  you should try  a couple of thing below:
This example work fine for me.

![imagen](https://user-images.githubusercontent.com/69447117/94172363-a6a62800-fe4f-11ea-8641-a0c7c825302d.png)

also, now we are able to use:
-Relavite path
-Absolute path

**Comment by Hamza-abughazaleh** [comment]
> up
> please solution for arabic characters using xhtml2pdf and pisa

Hi bassem, did you fix this issue?

**Comment by Hamza-abughazaleh** [comment]
> I have the same issue with Arabic characters.

Hi, did you solve the issue if yes what the font-family you use?

**Comment by pedroszg** [comment]
@Hamza-abughazaleh try out with DejaVuSans.ttf

**Comment by Hamza-abughazaleh** [comment]
> @Hamza-abughazaleh try out with DejaVuSans.ttf

I tried with it but the text show like that م ر ح ب ا and must be مرحبا

**Comment by pedroszg** [comment]
@Hamza-abughazaleh for arabic text you have to add a Custom tag, check this https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support

**Comment by Hamza-abughazaleh** [comment]
> @Hamza-abughazaleh for arabic text you have to add a Custom tag, check this https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support

also not work 🤷‍♂️ 
<img width="443" alt="Screen Shot 2020-09-25 at 12 16 05 PM" src="https://user-images.githubusercontent.com/32430159/94249673-e4c34a80-ff28-11ea-8e4f-cdbbb4c6e26c.png">

**Comment by pedroszg** [comment]
@Hamza-abughazaleh Can you show me your code?

**Comment by Hamza-abughazaleh** [comment]
> @Hamza-abughazaleh Can you show me your code?

<img width="788" alt="Screen Shot 2020-09-25 at 12 31 51 PM" src="https://user-images.githubusercontent.com/32430159/94251376-1b01c980-ff2b-11ea-9af4-61d386cbf5c5.png">

**Comment by pedroszg** [comment]
@Hamza-abughazaleh sorry, your html template

**Comment by Hamza-abughazaleh** [comment]
```
> @Hamza-abughazaleh sorry, your html template

{% load staticfiles %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE HTML>
<html>
<head>
    <title>Invoice for Order #{{ order.id }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="UTF-8">
    <style type="text/css">
		{% if LANGUAGE_CODE == 'ar' %}
			@font-face {
        		font-family: "Dejavu";
        		src: url('{% static "fonts/DejaVuSans.ttf" %}');
    		}
			body {
			    font-family: 'Dejavu';
				font-size: 14px;
				dir: rtl;
			}
			.details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
            }
            .order-detail {
            	text-align: right !important;
            }
		{% else %}
			body {
				font-size: 14px;
				dir: ltr;
			}
		    .details {
                padding: 10px 20px 0px 20px;
                text-align: right !important;
            }
            .order-detail {
            	text-align: left !important;
            }
		{% endif %}
		   	.order-detail {
            	border: 2px solid #A9A9A9;
            }
            .header {
                text-align: center;
                color: #FFF;
                background-color:#A9A9A9;
                padding: 10px 20px 0px 20px;
            }
            .order-card {
                color: #FFF;
                background-color:#A9A9A9;
                padding: 10px 20px 0px 20px;
            }
			.order-body {
				color: #000;
                padding: 10px 20px 0px 20px;
			}
            .title {
                font-size: 20px;
                font-weight: 100;
            }
            .title span {
                color: #000;
            }

    </style>
</head>
<body>
<pdf:language name="arabic"/>
    <span>رقم الغرفة:</span>
</body>
</html>
```

**Comment by pedroszg** [comment]
> > @Hamza-abughazaleh for arabic text you have to add a Custom tag, check this https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support
> 
> also not work 🤷‍♂️
> <img alt="Screen Shot 2020-09-25 at 12 16 05 PM" width="443" src="https://user-images.githubusercontent.com/32430159/94249673-e4c34a80-ff28-11ea-8e4f-cdbbb4c6e26c.png">

here you are using different text, could you copy the text?

**Comment by Hamza-abughazaleh** [comment]
> > > @Hamza-abughazaleh for arabic text you have to add a Custom tag, check this https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support
> > 
> > 
> > also not work 🤷‍♂️
> > <img alt="Screen Shot 2020-09-25 at 12 16 05 PM" width="443" src="https://user-images.githubusercontent.com/32430159/94249673-e4c34a80-ff28-11ea-8e4f-cdbbb4c6e26c.png">
> 
> here you are using different text, could you copy the text?

```
{% load staticfiles %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE>
<html>
<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="UTF-8">
    <style type="text/css">
		{% if LANGUAGE_CODE == 'ar' %}
			@font-face {
        		font-family: DejaVuSans;
        		src: url('{% static "fonts/DejaVuSans.ttf" %}');
    		}
			body {
			    font-family: DejaVuSans;
				font-size: 14px;
				dir: rtl;
			}
		{% else %}
			body {
				font-size: 14px;
				dir: ltr;
			}
		{% endif %}
    </style>
</head>
<body>
<div>
	<pdf:language name="arabic"/>
    <div>
        <h3> 1# فاتورة للطلب</h3>
    </div>
     <hr/>
     <div>معلومات الطلب</div>
</div>
</body>
</html>
```

**Comment by pedroszg** [comment]
> > > > @Hamza-abughazaleh for arabic text you have to add a Custom tag, check this https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support
> > > 
> > > 
> > > also not work 🤷‍♂️
> > > <img alt="Screen Shot 2020-09-25 at 12 16 05 PM" width="443" src="https://user-images.githubusercontent.com/32430159/94249673-e4c34a80-ff28-11ea-8e4f-cdbbb4c6e26c.png">
> > 
> > 
> > here you are using different text, could you copy the text?
> 
> ```
> {% load staticfiles %}
> {% load i18n %}
> {% get_current_language as LANGUAGE_CODE %}
> <!DOCTYPE>
> <html>
> <head>
>     <title></title>
>     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
> 	<meta charset="UTF-8">
>     <style type="text/css">
> 		{% if LANGUAGE_CODE == 'ar' %}
> 			@font-face {
>         		font-family: DejaVuSans;
>         		src: url('{% static "fonts/DejaVuSans.ttf" %}');
>     		}
> 			body {
> 			    font-family: DejaVuSans;
> 				font-size: 14px;
> 				dir: rtl;
> 			}
> 		{% else %}
> 			body {
> 				font-size: 14px;
> 				dir: ltr;
> 			}
> 		{% endif %}
>     </style>
> </head>
> <body>
> <div>
> 	<pdf:language name="arabic"/>
>     <div>
>         <h3> 1# فاتورة للطلب</h3>
>     </div>
>      <hr/>
>      <div>معلومات الطلب</div>
> </div>
> </body>
> </html>
> ```

![image](https://user-images.githubusercontent.com/69447117/94260776-fd623f00-feed-11ea-8d7d-c7bda034c106.png)

is this the result you want?

**Comment by Hamza-abughazaleh** [comment]
> > > > > @Hamza-abughazaleh for arabic text you have to add a Custom tag, check this https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support
> > > > 
> > > > 
> > > > also not work 🤷‍♂️
> > > > <img alt="Screen Shot 2020-09-25 at 12 16 05 PM" width="443" src="https://user-images.githubusercontent.com/32430159/94249673-e4c34a80-ff28-11ea-8e4f-cdbbb4c6e26c.png">
> > > 
> > > 
> > > here you are using different text, could you copy the text?
> > 
> > 
> > ```
> > {% load staticfiles %}
> > {% load i18n %}
> > {% get_current_language as LANGUAGE_CODE %}
> > <!DOCTYPE>
> > <html>
> > <head>
> >     <title></title>
> >     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
> > 	<meta charset="UTF-8">
> >     <style type="text/css">
> > 		{% if LANGUAGE_CODE == 'ar' %}
> > 			@font-face {
> >         		font-family: DejaVuSans;
> >         		src: url('{% static "fonts/DejaVuSans.ttf" %}');
> >     		}
> > 			body {
> > 			    font-family: DejaVuSans;
> > 				font-size: 14px;
> > 				dir: rtl;
> > 			}
> > 		{% else %}
> > 			body {
> > 				font-size: 14px;
> > 				dir: ltr;
> > 			}
> > 		{% endif %}
> >     </style>
> > </head>
> > <body>
> > <div>
> > 	<pdf:language name="arabic"/>
> >     <div>
> >         <h3> 1# فاتورة للطلب</h3>
> >     </div>
> >      <hr/>
> >      <div>معلومات الطلب</div>
> > </div>
> > </body>
> > </html>
> > ```
> 
> ![image](https://user-images.githubusercontent.com/69447117/94260776-fd623f00-feed-11ea-8d7d-c7bda034c106.png)
> 
> is this the result you want?

yes

**Comment by bassem79** [comment]
Hello hamza,
No i didn't found a solution...i abandon
all solutions proposed here doesn't work for me
i you found a solution for arabic characters please help me
thanks

**Comment by Hamza-abughazaleh** [comment]
@pedroszg the version I have is 0.2.4 and it's the latest version in the pip,  I checked the code, and this version doesn't have your changes

**Comment by pedroszg** [comment]
> @pedroszg the version I have is 0.2.4 and it's the latest version in the pip, I checked the code, and this version doesn't have your changes

yes, you are right, for now the changes about this issue are only in master

**Comment by Hamza-abughazaleh** [comment]
> pip install git+https://github.com/xhtml2pdf/xhtml2pdf.git#egg=xhtml2pdf

yes it's working fine, are you know when the new version will be release?

**Comment by luisza** [comment]
I hope, I can launch a new release  this weekend, all preparations are done, maybe @pedroszg can check the table issue before.

**Comment by Hamza-abughazaleh** [comment]
@luisza can you give me the status of the new release that fixes the Arabic characters?

**Comment by fbernhart** [comment]
@Hamza-abughazaleh 

Can you provide a full minimal example for the table issue?

**Comment by Hamza-abughazaleh** [comment]
@fbernhart I think the issue was solved because I reinstall pip install git+https://github.com/xhtml2pdf/xhtml2pdf.git#egg=xhtml2pdf and everything is good

**Comment by fbernhart** [comment]
@Hamza-abughazaleh Ok, great.

Because I was working on PR #520 today, writing some unittests for right-to-left writings, and couldn't see any issues with tables.

**Comment by WinThuLatt** [comment]
> > @pedroszg the version I have is 0.2.4 and it's the latest version in the pip, I checked the code, and this version doesn't have your changes
> 
> yes, you are right, for now the changes about this issue are only in master, cloud you please check using master using
> pip install git+https://github.com/xhtml2pdf/xhtml2pdf.git#egg=xhtml2pdf ? and remember include <pdf:language name="arabic"/> tag.

where should this tag go? i am facing similar issue for myanmar unicode. black blocks

**Comment by pedroszg** [comment]
Hi @WinThuLatt, the lastest version in ``the pip is 0.2.5``, please check this https://pypi.org/project/xhtml2pdf/ . About the tag, you have to put it in the body of your html.

**Comment by fbernhart** [comment]
@pedroszg @WinThuLatt 

As far as I can tell, this isn't about rendering fonts from right to left. According to Wikipedia Burmese (I guess this is the language we are talking about) is written from left to right.

Burmese doesn't seem to be supported by any standard-font like Arial, Helvetica etc. so this means that you have to define your own font. See: https://xhtml2pdf.readthedocs.io/en/latest/reference.html#using-custom-fonts


I was able to render some Burmese text by using the font "Myanmar Text", which was already on my Windows PC.


So use the following in the CSS part:

```
@font-face { font-family: MyBurmeseFont; src: url('C:\\Windows\\Fonts\\mmrtext.ttf') }
p { font-family: MyBurmeseFont }
```

In case you don't have the mmrtext.ttf file: you can use any other font you find on the internet, that supports Burmese.

Here is a testrendering that I did:
![image](https://user-images.githubusercontent.com/70264417/95763010-c8f0d000-0cae-11eb-9b4a-0ea34df7ab6d.png)

**Comment by pedroszg** [comment]
> @pedroszg @WinThuLatt
> 
> As far as I can tell, this isn't about rendering fonts from right to left. According to Wikipedia Burmese (I guess this is the language we are talking about) is written from left to right.
> 
> Burmese doesn't seem to be supported by any standard-font like Arial, Helvetica etc. so this means that you have to define your own font. See: https://xhtml2pdf.readthedocs.io/en/latest/reference.html#using-custom-fonts
> 
> I was able to render some Burmese text by using the font "Myanmar Text", which was already on my Windows PC.
> 
> So use the following in the CSS part:
> 
> ```
> @font-face { font-family: MyBurmeseFont; src: url('C:\\Windows\\Fonts\\mmrtext.ttf') }
> p { font-family: MyBurmeseFont }
> ```
> 
> In case you don't have the mmrtext.ttf file: you can use any other font you find on the internet, that supports Burmese.
> 
> Here is a testrendering that I did:
> ![image](https://user-images.githubusercontent.com/70264417/95763010-c8f0d000-0cae-11eb-9b4a-0ea34df7ab6d.png)

@fbernhart yes, you are right thank for your help.
@WinThuLatt sorry I didn't see that your issue is about black blocks

**Comment by muneermohd9690** [comment]
guys arabic text display is working.please try to change fonts along with the prosposed solutions here.you might check my sen-receive project in github and see if that helps you.thanks.
https://github.com/muneermohd9690

**Comment by fbernhart** [comment]
@muneermohd9690 

What do you mean by changing the fonts? You can use your own custom font like this:

https://xhtml2pdf.readthedocs.io/en/latest/reference.html#using-custom-fonts

**Comment by muneermohd9690** [comment]
> @muneermohd9690
> 
> What do you mean by changing the fonts? You can use your own custom font like this:
> 
> https://xhtml2pdf.readthedocs.io/en/latest/reference.html#using-custom-fonts
Yes you can.but the thing is only some fonts are supported.some are not.you can check my repositories for the one named sent-receive-project.I have an html for printing a pdf which contains Arabic characters.

**Comment by fbernhart** [comment]
@muneermohd9690 

Please provide a short example to reproduce the error. I'm not gonna browse through all the files in your repository.

As well please consider to open a new issue, so we can discuss it there. Thanks

**Comment by jergus48** [comment]
> Me too. Slaven characters, 3 of 5 work, the other 2 do not work. Changing fonts makes me even bigger problems.

have you found solution please?

**Comment by timobrembeck** [comment]
@jergus48 For me, [Open Sans](https://fonts.google.com/specimen/Open+Sans) worked pretty well with Cyrillic/Slavic scripts.
If this doesn't work for you, please open a new issue with the specific characters you're trying to render and the fonts you have tried so far.

**Comment by jergus48** [comment]
Thanks for reply🙏

**Comment by akashsagar8** [comment]
### **problem-----I m using xhtml2pdf library for converting html into pdf for HINDI language --- but not working it gives**


hello :■■■■ ■■■■ ■■ ■■
myname:■■■■■■■■■■■■■■■■■■
fathername:■■■■■■■■■■■■■■■ ■■■■■■■■


**this is my view of python--------**

def show_products(request):
    products = crudajax.objects.filter(delete_flag=False).all()
    template_path = 'pdf_report.html'
    context = {'products': products}

   
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'

    template = get_template(template_path)
    html = template.render(context)
 
    result = BytesIO()

    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result, encoding='UTF-8')

   
    if not pdf.err:
      return HttpResponse(result.getvalue(), content_type='application/pdf')
    if pdf.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')

    return response


-----------------------------this is my html header------------------------------
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap/css/bootstrap.min.css'%}"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/js/'%}" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://unpkg.com/html2pdf.js/dist/html2pdf.bundle.js"></script>
    <style>
      @page {
        size: letter landscape;
        margin: 2cm;
      }
      @font-face {
        font-family: "Noto Sans Devanagari";
        /* src: url('https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari&display=swap'); */
      }
      body {
        font-family: "Noto Sans Devanagari", sans-serif;
      }


plz solve anyone this issue-----

**Comment by stefan6419846** [comment]
@akashsagar8 Please prefer opening a new issue with a standalone example to not loose overview. By the way: With the `< >` button above the GitHub editor you can format your code snippets nicely.

**Comment by akashsagar8** [comment]
> @akashsagar8 Please prefer opening a new issue with a standalone example to not loose overview. By the way: With the `< >` button above the GitHub editor you can format your code snippets nicely.

**Comment by akashsagar8** [comment]
this is my html pdf ........................... i used already noto devnagri-regilar.ttf

**Comment by akashsagar8** [comment]
can anyone solve this issue.. if yes plz send me your email ... i will give you my files

**Comment by jergus48** [comment]
Same for me, I have still this problem on windows computer, on macbook it
is working. I can send you my files if there is someome skilled in this
problem. Thanks

Dňa ut 2. 1. 2024 o 13:04 Akash ***@***.***> napísala(a):

**Comment by stefan6419846** [comment]
As already mentioned above: Please create a new issue with a clear and concise description and corresponding (minimal) code which reproduces your issue. While there might be cases with personal support, FOSS projects generally live from public community-driven support and it simplifies stuff if some aspects are generic and provides some easy way to get a grasp of it for future readers.

**Comment by akashsagar8** [comment]
problem---> I m converting html (hindi language) into pdf but hindi font is not encodied it gives some unreadable character like this



hello :■■■■ ■■■■ ■■ ■■
myname:■■■■■■■■■■■■■■■■■■
fathername:■■■■■■■■■■■■■■■ ■■■■■■■■

these black boxes is the hindi text,

what I used to solve this problem---
utf-8 in html,
devnagri-regular.ttf,
but problem is not solvd 

if anyone can solve this plz contect me on my email or number ----akashsagar8775@gmail.com, 8445318775-whatshap number

**Comment by akashsagar8** [comment]
> As already mentioned above: Please create a new issue with a clear and concise description and corresponding (minimal) code which reproduces your issue. While there might be cases with personal support, FOSS projects generally live from public community-driven support and it simplifies stuff if some aspects are generic and provides some easy way to get a grasp of it for future readers.

ok i repost my problem you can see

**Comment by stefan6419846** [comment]
> ok i repost my problem you can see

You just added another comment to this old issue. Please go to https://github.com/xhtml2pdf/xhtml2pdf/issues/new/choose and open a new one. Make sure to provide a minimal HTML file, the minimal Python code and corresponding inputs in a way that (in the best case) just running the Python code - without further special setup - yields to your problem.

**Comment by akashsagar8** [comment]
ok i will soon

**Comment by akashsagar8** [comment]
hello sir ... I created a issue on site ----

https://github.com/xhtml2pdf/xhtml2pdf/issues/744   this is the link
