### ISSUE TITLE
Non ASCII Japanese characters not rendered

### ISSUE THREAD

**Issue by gauravt1** [xhtml2pdf/xhtml2pdf#353]
I am currently using xhtml2pdf 0.0.6 and I have installed a japanese  font on my system. I'm also providing @font-face css as below - 

    @font-face { 
            font-family: "DejaVuSansMono"; 
                    src: url({{data.font_url}}) 
            }

            html { 
                    font-family: "DejaVuSansMono", sans-serif; 
            }

But unfortunately it comes up with black boxes instead of japanese text. Below is the code snippet in which I am passing arguments to pisaDocument - 

	result = CStringIO.StringIO()
	encoded_html = CStringIO.StringIO(html.encode("UTF-8"))
	pdf = pisa.pisaDocument(encoded_html, result, debug=1, encoding='UTF-8')
	if not pdf.err:
		if int(embed) == 1:
			return HttpResponse(result.getvalue(), content_type='application/pdf')
		response = HttpResponse(result.getvalue(), content_type='application/octet-stream', status=200)

		response['Content-Disposition'] = "attachment; filename=PDF Summary-"+str(model_obj.field_id).zfill(5)+".pdf"
		return response

I don't understand where I am doing wrong. Please advise

**Comment by gauravt1** [comment]
Can anyone please suggest some fix?

**Comment by luisza** [comment]
url({{data.font_url}})  look like an internal url, so the generated html there have http://domain part?

**Comment by gauravt1** [comment]
Yes is has.

**Comment by LegoStormtroopr** [comment]
Try upgrading to version 0.2b and try again. If it isn't working there I can try and determine a fix for it.

**Comment by LegoStormtroopr** [comment]
It seems this is a font issue in reportlab that I can't figure out.

**Comment by luisza** [comment]
PR #505 Fixed Asian font support, but checking the font used in the example this font has not support to Japanese characters.
We checked with other fonts that has support Japanese and worked.
