### ISSUE TITLE
how to generate pdf by using localhost(http not https)

### ISSUE THREAD

**Issue by RobertRajcool** [xhtml2pdf/xhtml2pdf#355]
HI i am trying to convert html to pdf by using xhtml2pdf,in that how to use with http,whether its possible to generate using localhost(http)

        from django.template.loader import get_template
        from django.template import Context
        from io import StringIO, BytesIO
        import xhtml2pdf.pisa as pisa
        fileName = screename + '.pdf'
        template_Data = {'screenName': screename,
                         'tableheaders': extraoptions,
                         'tablebodycontent': queryset
                         }
        message = get_template('red-pdf-list.html').render(Context(template_Data))
        result = StringIO()
        #encoded_html = StringIO(message.encode("UTF-8"))
        pdf = pisa.pisaDocument(message, result, debug=1, raise_exception=False)
        if not pdf.err:
            return HttpResponse(result.getvalue(), content_type='application/pdf')
        return True
i got error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

**Comment by luisza** [comment]
Use link_callback instread to localhost request see the doc

http://xhtml2pdf.readthedocs.io/en/latest/usage.html#using-xhtml2pdf-in-django
