### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by luisza** [xhtml2pdf/xhtml2pdf#356]
Hi,

I am worry about this project because I pull request are not merged faster (6 months approx) and issues grown with few answers.

I know only one person is merging PR and reviewing code and that is a lot of work.

I want to help but I don't want to wait a year for view pull request merged, I was offer me as owner of project  but now owner is set and is working so maybe I can help as collaborator and help to merge PR

**Comment by LegoStormtroopr** [comment]
Unfortunately, I've been busy at work and that has limited my time to maintain this project. 

If there are any high priority issues you'd like to see addressed, please bump those and I'll see what I can do.

**Comment by benjaoming** [comment]
Hi @luisza - I've added you as a collaborator seeing that you work actively on this project and there's a lack of activity otherwise and PRs going to waste.

**Comment by luisza** [comment]
Hi, thanks 
I'm going to take time next week to check some PR
