### ISSUE TITLE
Wrong operand type issue

### ISSUE THREAD

**Issue by apiljic** [xhtml2pdf/xhtml2pdf#358]
Hello,

I am trying to use this library in a django app.
The view is defined as:
```
def test_pdf(request, id, slug, language=None):
    html = test(request, id, slug, language, pdf=True)
    destination = StringIO()

    pdf = pisa.pisaDocument(StringIO(html.encode('utf-8')), destination, encoding='utf-8')

    if not pdf.err:
        response = HttpResponse(destination.getvalue(), content_type='application/pdf')
        response['Content-Disposition'] = 'filename=test.pdf'
        return response
    else:
        return HttpResponse("Error: <pre>%s</pre>" % escape(html))
```

And the html:
```
<!DOCTYPE html>
<html lang="en">
</head>
<body>
    test
</body>
</html>
```

What I get out is a test.pdf which opens nicely in Adobe Reader, but in Adobe Acrobat gives a "Wrong operand type" error.

File:
[test.pdf](https://github.com/xhtml2pdf/xhtml2pdf/files/1115145/test.pdf)

I was wondering if you are familiar with this error and whether or not the pdfs produced with this library can be opened with Acrobat?

Thank you!

**Comment by GautierT** [comment]
Hi @apiljic , 
i have the same issue. Did you find a solution ? Thanks.

**Comment by apiljic** [comment]
Hello!
Unfortunately not. I was not able to solve this problem. I will look at it again when I have some time, but if I find no solution, then I'll have to generate pdfs in a different way.
In case I find a way to fix it, I'll upload the solution here.
Cheers!

**Comment by GautierT** [comment]
Thanks a lot for your answer.

I tested with this script and it's working without trouble.
```
from xhtml2pdf import pisa             # import python module

# Define your data
sourceHtml = """<html>
<head>
<style>
    @page {
        size: letter portrait;
        @frame header_frame {           
            -pdf-frame-content: header_content;
            left: 50pt; width: 512pt; top: 50pt; height: 40pt;
        }
        @frame col1_frame {             
            left: 44pt; width: 245pt; top: 90pt; height: 632pt;
        }
        @frame col2_frame {             
            left: 323pt; width: 245pt; top: 90pt; height: 632pt;
        }
        @frame footer_frame {           
            -pdf-frame-content: footer_content;
            left: 50pt; width: 512pt; top: 772pt; height: 20pt;
        }
    }
</style>
<head>

<body>
    <div id="header_content">Lyrics-R-Us</div>
    <div id="footer_content">(c) - page <pdf:pagenumber>
        of <pdf:pagecount>
    </div>
    <p>Old MacDonald had a farm. EIEIO.</p>
    <p>And on that farm he had a cow. EIEIO.</p>
    <p>With a moo-moo here, and a moo-moo there.</p>
    <p>Here a moo, there a moo, everywhere a moo-moo.</p>
</body>
</html>"""
outputFilename = "test.pdf"

# Utility function
def convertHtmlToPdf(sourceHtml, outputFilename):
    # open output file for writing (truncated binary)
    resultFile = open(outputFilename, "w+b")

    # convert HTML to PDF
    pisaStatus = pisa.CreatePDF(
            sourceHtml,                # the HTML to convert
            dest=resultFile)           # file handle to recieve result

    # close output file
    resultFile.close()                 # close output file

    # return True on success and False on errors
    return pisaStatus.err

# Main program
if __name__=="__main__":
    pisa.showLogging()
    convertHtmlToPdf(sourceHtml, outputFilename)
```

Which version of Adobe Acrobat are you using ?
And which xhtml2pdf version ?
I'm using xhtml2pdf==0.0.6 and html5lib==1.0b8

**Comment by apiljic** [comment]
Hi!
I understand.

I am (was) using:
xhtml2pdf==0.2b1
html5lib==1.0b8
Acrobat 7.0 Professional.
I am not sure about other Acrobat versions.

I now switched to 0.0.6 and I can confirm that the error message in Adobe Acrobat is gone.
I have to double check that really everything is fine, but it looks like the older version may be fine.

So the problem arose sometime between 0.0.6 and 0.2b1.

Thanks a lot for sharing your script and version details! I really appreciate it.
Cheers!

**Comment by GautierT** [comment]
On more recent Acrobat version the PDF file generated with 0.2b1 are working correctly but not with older version like 7.0.

And yes, the problem is between 0.0.6 and 0.2b1.

You're welcome ! 

Cheers.

**Comment by apiljic** [comment]
Hi @GautierT  
I just tried to upgrade to 0.2.3. I can still see this issue when trying to open pdf files with Acrobat Professional 7.0.
I assume the newer versions will not attempt to make pdf files compatible with those older Acrobat versions, or?
So I guess I could continue using 0.0.6 until I upgrade to python 3, and then upgrade and ignore the issue with the old Acrobat.

**Comment by stefan6419846** [comment]
Is this really still an issue? Has anyone been able to test this with PDF files generated by an up-to-date xhtml2pdf, *reportlab*, *pypdf* and Adobe Acrobat?

**Comment by apiljic** [comment]
I just tested pdf files generated with xhtml2pdf==0.2.8 and can confirm they open even in older Adobe Acrobat.
