### ISSUE TITLE
How to set the width?

### ISSUE THREAD

**Issue by bool-dev** [xhtml2pdf/xhtml2pdf#360]
Does setting the width not work?

    <style type="text/css">
    @page {
        size: a4 landscape;
        width: 27cm;  /* not working */
        @frame content {
            top: 2cm;
            width: 27cm;  /* not working */
            margin-left: 1.5cm;  /* changing these values work!! */
            margin-bottom: 2cm;  /* changing these values work!! */
        }
    }
    </style>

**Comment by kamilturek** [comment]
@bool-dev 
`@page` does not support `width` property. If you would like to set custom document width you can achieve this by providing a tuple as a `size` property:

```html
<style>
    @page {
        size: 27cm 5cm;
    }
</style>
```
