### ISSUE TITLE
gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by sandeepsayone** [xhtml2pdf/xhtml2pdf#365]
Getting this error while trying to download a pdf. It happens  in https, when i try to render an image in the pdf from an external https url.

`File "/usr/lib/python2.7/socket.py", line 553, in create_connection
  for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known`

**Comment by luisza** [comment]
Solved en 2.0 version
