### ISSUE TITLE
Tallest cell 836.9 points,  too large on page 12 in frame u'content_frame'(475.0 x 730.0*) of template 'body'

### ISSUE THREAD

**Issue by edebruyne** [xhtml2pdf/xhtml2pdf#371]
Hello i have this error on one of my pdf generation.
836px for body is vastely out of my A4 format so i can't even try to match this size with template.

What can i do ? 

Flowable <PmlTable@0x7F5833383290 49 rows x 1 cols(tallest row 836)> with cell(0,0) containing
'<PmlKeepInFrame at 0x7f583170fdd0> size= maxWidth=467.5x maxHeight=836.8898'(475.0 x 4236.63968478), tallest cell 836.9 points,  too large on page 12 in frame u'content_frame'(475.0 x 730.0*) of template 'body'

**Comment by giovanniborella** [comment]
i got around the same error by following the[ docs here](https://xhtml2pdf.readthedocs.io/en/latest/reference.html#long-cells)

basically add `table {    -pdf-keep-in-frame-mode: shrink;}` or another mode

**Comment by allexiusw** [comment]
> i got around the same error by following the[ docs here](https://xhtml2pdf.readthedocs.io/en/latest/reference.html#long-cells)
> 
> basically add `table { -pdf-keep-in-frame-mode: shrink;}` or another mode

It worked for me! Thanks a lot... I have an advice I will write it down later in the thread.
The option I used was:
`body { -pdf-keep-in-frame-mode: shrink;}` because the frame I had problems with was body.

**Comment by stefan6419846** [comment]
As this is apparently mentioned inside the official docs and has been resolved, is there still any value or something to do on this issue?
