### ISSUE TITLE
I need to step back as a maintainer

### ISSUE THREAD

**Issue by LegoStormtroopr** [xhtml2pdf/xhtml2pdf#373]
I've been neglecting my repsonsibilities to this project.

While I was happy to take it on, and help curate other contributors Python3 support into the codebase, I have to step back.

Apologies to anyone who is still using this. :(

**Comment by luisza** [comment]
Hi, @LegoStormtroopr , I offer me to be a main maintainer of this project if none one wants.  I am now collaborator and think, one of the most interested in this project.   I really wants that this project don't die and I think I could help. 

I really interested in forward to new version of this beta state that have months with out new release, so maybe I if I convert in main maintainer i need pypi access to release a new beta 0.2b2.

**Comment by bogdanpetrea** [comment]
Any news on this issue?

**Comment by luisza** [comment]
Hi, I am answering issues actively, and also making, reviewing, and merging PR.
I also repairing testrender tests, so I think is not dead but a lot of help is need it.

**Comment by benjaoming** [comment]
> so maybe I if I convert in main maintainer i need pypi access to release a new beta 0.2b2.

It would always help to ask ;)

Do you know how to make signed releases, and do you have a PGP key?

**Comment by luisza** [comment]
> Do you know how to make signed releases, and do you have a PGP key?

Yes, I do.

This is my gpg public key
```
gpg --keyserver pool.sks-keyservers.net --search-keys '633B544CD5F72811'
```

**Comment by benjaoming** [comment]
Awesome, one more thing: What's your PyPi username?

...This info might seem inappropriate -- why not just an email? Answer is that this is actually highly relevant for public domain :)

**Comment by luisza** [comment]
> it's still important to keep expectations low and make sure that real development happens in WeasyPrint instead 

I agree with you, but i think xhtml2pdf is not die and many people are interested in it, also many project depends of this project.  Also as you can see son PR was merged in the last months and new functionalities was included like urllib2 options for skip certificate validation.

I use both software and think xhtml2pdf it's better in some cases like performance, but weasyprint have a better support for css. So I will try to incorporate tinycss2 as css parser (work in process)

**Comment by benjaoming** [comment]
Can you confirm that your username on PyPi is luisza ?

**Comment by luisza** [comment]
Yes, It is

**Comment by benjaoming** [comment]
Alright, you're in :)

**Comment by LegoStormtroopr** [comment]
Thanks folks. I was glad to have acted as caretaker on this for a while.

**Comment by MartinThoma** [comment]
@LegoStormtroopr Is the project currently not maintained? What do you think about moving it to the `py-pdf` organization? https://github.com/py-pdf

**Comment by benjaoming** [comment]
@MartinThoma the project is being maintained by @luisza - I think this issue can be closed.

**Comment by luisza** [comment]
@MartinThoma  sorry the delay on answer, I think it's better if xhtml2pdf continue as separate organization, but if you want to incorporate as maintainer we can collaborate to improve xhtml2pdf.

**Comment by MartinThoma** [comment]
I really don't want to become the maintainer of another project :sweat_smile: `pypdf` / `PyPDF2` already take a lot of energy / time and I'm also writing `flake8-simplify`.

I'm very happy that you maintain `xhtml2pdf`  :-)
