### ISSUE TITLE
Unable to load images using xhtml2pdf on the server

### ISSUE THREAD

**Issue by JeevanJB** [xhtml2pdf/xhtml2pdf#375]
I am using Django 1.11 with Python 3.6, I have installed "--pre xhtml2pdf" for my HTML to PDF conversion. In my HTML file I have a image, the image is placed in same directory <for convenience> as that of HTML file. The image is described in simple manner as shown <img src="logo.png">
I get the image on localhost, however when I run it on server, I am not able to get the image.
I have referenced this link: https://github.com/xhtml2pdf/xhtml2pdf 
Can you please guide on this.

**Comment by luisza** [comment]
Hi, 
Please see before http://xhtml2pdf.readthedocs.io/en/latest/usage.html#using-xhtml2pdf-in-django

**Comment by JeevanJB** [comment]
Thanks luisza. It worked well
