### ISSUE TITLE
Httplib options not visible when is installed via pip

### ISSUE THREAD

**Issue by juhunuque** [xhtml2pdf/xhtml2pdf#385]
Hello, recently was added support to httplib options (https://github.com/xhtml2pdf/xhtml2pdf/pull/378). When I try to install xhtml2pdf using `pip install xhtml2pdf --pre` seems like is loading an old version because the new httpconfig is not found. Whether I install it from github, it works fine. I'd rather if I can install it using `pip install xhtml2pdf --pre` and not from git. Am I missing something?

**Comment by luisza** [comment]
Well today 0.2.1 was release and have the last master code so httplib options are included in this release :)
