### ISSUE TITLE
Using `<pdf:pagenumber>` outside `footer_content` prints 0

### ISSUE THREAD

**Issue by bukovyn** [xhtml2pdf/xhtml2pdf#389]
Running into some trouble where `<pdf:pagenumber>` is working as intended in the footer div, but when trying to display page number as `<div> Page <pdf:pagenumber> of <pdf:pagecount> </div>`,  `<pdf:pagecount>` returns null and the html displays `Page X of  ' '`.

**Comment by timoludwig** [comment]
Duplicate of #322
