### ISSUE TITLE
update html5lib depencency

### ISSUE THREAD

**Issue by last-partizan** [xhtml2pdf/xhtml2pdf#390]
Hello.
Is there any reason to force version for html5lib to 1.0b10?

I just tested html5lib==1.0.1 and it works just fine.

**Comment by overshard** [comment]
This is also a problem for me, most of my other libs are conflicting with this one due to the specification of 1.0b10 for Pipfile locking using pipenv.

**Comment by last-partizan** [comment]
Looking at #373, i think this is not actively maintained anymore, so they pinned deps to support legacy installs. I just switched to weasyprint, as recommended in readme.

**Comment by luisza** [comment]
The Project is not death, but  we are few active maintainer so PR are welcome and will be check faster than features requests.

**Comment by browniebroke** [comment]
This seems to be the only unreleased meaningful change. Looks pretty low-risk. Would you have a minute to make a new release? Then this issue can be closed, I think.
