### ISSUE TITLE
Git tags for new releases

### ISSUE THREAD

**Issue by browniebroke** [xhtml2pdf/xhtml2pdf#393]
When a new third-party package is released, it's convenient to be able to compare what changed in it. Github enables this via git tags, you can compare changes between releases, e.g.:

https://github.com/xhtml2pdf/xhtml2pdf/compare/0.2...0.2.1

However, it seems the tags for 0.2.1 and 0.2.2 are missing from GitHub, could the tags be pushed to GitHub, please? I assume it's because they were not pushed using `git push --tags` (I always forget to push the tags myself...)?

Thanks

**Comment by luisza** [comment]
Sorry, I create a new tag and new release.
