### ISSUE TITLE
Custom pagesize

### ISSUE THREAD

**Issue by JosielWirlino** [xhtml2pdf/xhtml2pdf#400]
As the xhtml2pdf wrapper reportlab should be a resource add custom-page-size tag and leave the dev be responsible how it works. I'm facing a problem that my pdf it is a  80mmx 60mm and it's a pain do that with xhtml2pdf. Actually I didn't it work, so far. 
Probably I will user reportlab but when xhtml2pdf support it will be great.

**Comment by luisza** [comment]
Hi, you can do it with the existing code, just add in your header 
<style>
    @page {
        size: 80mm 60mm;
    }
</style>

I checked and works like a charm.
