### ISSUE TITLE
Blank PDF for some clients

### ISSUE THREAD

**Issue by nexgentech5601** [xhtml2pdf/xhtml2pdf#403]
We are able to successfully generate PDFs and for most of our users they are able to see it  but for a select few they get a blank PDF when they download. Most of the people with issues are using older versions of Adobe, would that cause an issue? If yes, is there a way around it?

**Comment by michaeltmayo** [comment]
I am having the same issue I believe. It is hard to replicate. Did you find a solution for this? @nexgentech5601

**Comment by garvit4512** [comment]
Facing the same issue, specifically with Adobe Reader 9. I tried rendering the simplest pdf (just one word in <body>) and it still shows empty.

**Comment by timoludwig** [comment]
As long as there is no information on how to reproduce this, I'm going to close it.
Feel free to provide more details so we can reconsider this.
