### ISSUE TITLE
Justify align not working when I Mark html string as safe (safe template tag) 

### ISSUE THREAD

**Issue by vinigracindo** [xhtml2pdf/xhtml2pdf#407]
![img_20180816_004332](https://user-images.githubusercontent.com/999040/44186126-fc933800-a0ed-11e8-903f-cce75fd1b04e.jpg)

![img_20180816_004317](https://user-images.githubusercontent.com/999040/44186129-06b53680-a0ee-11e8-8413-41273d9cfd54.jpg)

Can someone help me?

**Comment by ldonjibson** [comment]
I encountered the same issue also doto the model and do something of this nature
```
    def tmake_safe(self):
        if self.descritption:
            getduty = mark_safe(self.descritption)
            return getduty
        else:
            return None
```
where "descritption" is the model field you are trying to mark safe
remember to import mark_safe 
`from django.utils.safestring import mark_safe
`

**Comment by timoludwig** [comment]
This has nothing to do with this library, but it's a Django-specific problem instead.
