### ISSUE TITLE
Css doesn't work as static file

### ISSUE THREAD

**Issue by hybridpicker** [xhtml2pdf/xhtml2pdf#408]
When I am loading my CSS-File with "{% load staticfiles %}" doesn't effect the PDF.
<link rel="stylesheet" href="{% static 'css/bills.css' %}">

Getting this as a print:
<link rel="stylesheet" href="/static/css/bills.css"> 
An with  "/" it doesn't work...

Wth a normal link it works proper:
  <link rel="stylesheet" href="static/css/bills.css">

**Comment by luisza** [comment]
Are you linking link_callback well ?
https://xhtml2pdf.readthedocs.io/en/latest/usage.html#using-xhtml2pdf-in-django
