### ISSUE TITLE
Latin-1 coding error!!

### ISSUE THREAD

**Issue by dcruz1990** [xhtml2pdf/xhtml2pdf#439]
When using with Django 2.0.6:

Request Method: | GET
-- | --
http://127.0.0.1:8000/generatepdf
2.0.6
UnicodeEncodeError
'latin-1' codec can't encode character '\ufeff' in position 0: ordinal not in range(256)

in this line:
` pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result) `

**Comment by Swixx** [comment]
@dcruz1990 Please refer to my comment in #434

**Comment by daniloarodrigues** [comment]
Can you show me your code?

**Comment by timobrembeck** [comment]
@dcruz1990 without further information, we are not able to work on this ticket. If the issue still persists, please provide some details including the html code you are trying to render.
