### ISSUE TITLE
Not able to open a link in new tab

### ISSUE THREAD

**Issue by sunilplivo** [xhtml2pdf/xhtml2pdf#446]
I have a link in my html file to our website, which I want to open in a new tab. Using `target="_blank"` does not seem to be working.

How can create a link in html file which when converted to pdf using xhtml2pdf should open in a new tab?

**Comment by divurgentuser** [comment]
Use response['Content-Disposition'] = 'inline' instead of 'attachment'

**Comment by Tanujshriyan** [comment]
Was this issue fixed? the above `response['Content-Disposition'] = 'inline'` doesn't seem to be working anymore.
