### ISSUE TITLE
Arabic characters rendered separated 

### ISSUE THREAD

**Issue by megamayoy** [xhtml2pdf/xhtml2pdf#494]
I am using xhtml2pdf with Django. so basically I have a template that has Arabic content
```html
<html xmlns="http://www.w3.org/1999/xhtml" lang='ar' xml:lang="ar" dir="rtl">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<style>

        @font-face {
        font-family: "DejaVuSans";
        src: url('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf');
    }
    body {
    font-family: "DejaVuSans";
    text-align: center;
}


</style>
</head>
<body>
<div>
<span class="field-label" style="font-weight: bold;margin-right: 5px">رقم الغرفة:</span>
</div>
```
**rendering this to PDF resulted in** 
![sc1](https://user-images.githubusercontent.com/11338579/84139924-0c150b00-aa51-11ea-8925-b76efd75ac90.png)

Desired result:

![sc](https://user-images.githubusercontent.com/11338579/84139959-1b945400-aa51-11ea-8e95-bc0ce0c3f9ec.png)

**Comment by garvit4512** [comment]
Facing the same issue with Hindi characters. Tried many different fonts but no dice. From what I've understood this is a issue with ReportLab/Pillow itself being unable to render it correctly.

**Comment by pedroszg** [comment]
You can check https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support about a new 'Custom Tag' to avoid this kind of issue.

**Comment by muneermohd9690** [comment]
thanks for the code.arabic langugae is working.please guys try to change the fonts for respective languages.because some fonts won't work.

**Comment by AissaNouacer** [comment]
https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support , follow the instruction on the docs all you need to insert is <pdf:language name="arabic"/> it's a special tag for xhtml2pdf.

**Comment by muneermohd9690** [comment]
> https://xhtml2pdf.readthedocs.io/en/latest/reference.html#asian-fonts-support , follow the instruction on the docs all you need to insert is <pdf:language name="arabic"/> it's a special tag for xhtml2pdf.

thank you.it has been applied on the same day i made the request and is working well.
