### ISSUE TITLE
Putting a left border on a div with a heading in it causes a ValueError('Unknown color %r' % aColor)

### ISSUE THREAD

**Issue by ndunn219** [xhtml2pdf/xhtml2pdf#495]
Putting a left border on a div with a heading in it causes a ValueError('Unknown color %r' % aColor).

### Given the following **sample.html** file:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Test</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
  div {
    border-left-style: solid;
  }
</style>
</head>
<body>
  <div>
    <h1>a</h1>
  </div>
</body>
</html>
```
### Run:
`xhtml2pdf sample.html`

### Result
```
 File "...\lib\site-packages\reportlab\pdfgen\textobject.py", line 135, in setStrokeColor
    raise ValueError('Unknown color %r' % aColor)
ValueError: Unknown color False
```

### Notes

1. I've tested replacing the h1 with h2, h3, h4, h5, and h6. All of those cause the same error. Other tags (e.g., p, div) don't cause the error.
2. I've tested borders on the other sides (e.g., top, right, bottom). None of those result in an error.

**Comment by mm-matthias** [comment]
Is this a duplicate pf #466 ?

**Comment by fbernhart** [comment]
@ndunn219 I just tested your example and it indeed seems like a duplicate to #466. It isn't working in the current version 0.2.4, but PR #467 fixed this. So with the next official release (0.2.5) you should be able to use "border-left-style" without problems.

@luisza can probably close this issue.
