### ISSUE TITLE
Supported Python Versions?

### ISSUE THREAD

**Issue by fbernhart** [xhtml2pdf/xhtml2pdf#511]
In my opinion it would be great to be very clear on which Python versions xhtml2pdf is supporting.
The case right now is like the following:

- README.rst is stating:
"Python 2.7+. Only Python 3.4+ is tested and guaranteed to work."

- With Travis CI we are testing versions: 3.5, 3.6, 3.7, 3.8 and pypy3.

- With Appveyor CI we are testing versions: 2.7, 3.5 and 3.6

- Some of the code base is still written in Python 2. 
For example context.py, line 172:
`if isinstance(part, basestring):`
Which will lead to an error in any Python 3 version because basestrings were only used in Python 2.

**I think it would be a great idea to find a common ground to work on and to agree which Python versions should be supported and which shouldn't anymore.** Let me just note here, that Python 2.7 is already "end of life" and not supported anymore since January 2020. Python 3.4 has reached it's end-of-life already in May 2019 and the support for Python 3.5 will officially end in just 2 days (end of September 2020). Meanwhile Python 3.9 will be released in about a week.

So in my opinion it would be a good idea to only support and test Python 3.6 to Python 3.9. Especially I see a conflict in still supporting Python 2, as this will make it harder to implement new features. Also I guess we could cleanup the code base and probably also gain some performance, if we focus on using and supporting Python 3.6 and above.

By dropping Python 2 support, we probably could also get rid of the "six" dependency. As its only purpose seems to be to make code compatible with Python 2 and 3.

Let me know what you think!

P.S.: The same discussion should probably also be held about the ReportLab versions that we support. But I'll better open up another issue about that.

**Comment by tieugene** [comment]
In addition: py3.9 and py3.10 absent in tox.ini

**Comment by fbernhart** [comment]
@tieugene xhtml2pdf doesn't seem to be actively maintained.

**Comment by captn3m0** [comment]
I added 3.9 and 3.10 in tox in https://github.com/xhtml2pdf/xhtml2pdf/pull/582, but Appveyor seems to be ignoring most of these. Is there a limit somewhere?
