### ISSUE TITLE
"name 'basestring' is not defined" error thrown on master (no Python 3 support)

### ISSUE THREAD

**Issue by ahmedosama94** [xhtml2pdf/xhtml2pdf#513]

**Comment by luisza** [comment]
You need to include more information about this issue.

**Comment by fbernhart** [comment]
> You need to include more information about this issue. 

I guess it should be context.py, line 172, as stated in issue #511.

At least this is the only part of the xhtml2pdf code, that uses 'basestring'.

**Comment by ahmedosama94** [comment]
@luisza apologies, yes @fbernhart is right, it's in context.py line 172. I intended to create a pull request with the fix since I need this ASAP, but I couldn't get to push a new branch.

**Comment by fbernhart** [comment]
@ahmedosama94 

As it's just one line of code to change, I can also quickly create a PR to fix it. Just give me some few hours, I'm busy now.

@luisza then just has to merge it.
