### ISSUE TITLE
Exception in context.py related to font names

### ISSUE THREAD

**Issue by leetncamp** [xhtml2pdf/xhtml2pdf#530]
The new code in 0.2.5 shown below assumes the variable names is a string when it's actually a list of strings. In line 836,  if `names.startswith("#"):` causes the exception.

        ```
# XXX Just works for local filenames!
        if names and src:
            file = src
            src = file.uri
            log.debug("Load font %r", src)
            if names.startswith("#"): …
                names = names.strip('#')
            if type(names) is ListType:
                fontAlias = names
            else:
                fontAlias = (x.lower().strip() for x in names.split(",") if x)
```

**Comment by fbernhart** [comment]
Have you already seen #522 ? So this issue should already be fixed.

If you want, you could try to run the master branch of xhtml2pdf and see if there is still a problem.

**Comment by leetncamp** [comment]
Sorry! I looked for a similar issue but didn't see that.  This issue and my issue are the same. 

You may delete mine. Thanks for writing. 




--Lee--

**Comment by fbernhart** [comment]
You're welcome. :)

You can just close it yourself. I don't have the permissions to.
