### ISSUE TITLE
Set object in specific part of single page only

### ISSUE THREAD

**Issue by Roman914** [xhtml2pdf/xhtml2pdf#547]
As I see, right now placing object in specific part of the page is possible only using Frames,

I have a situation that I need to place some image in bottom of the last page **only**, and the data before isn't fixed size, so I can't use margin for example to solve it.

Did anyone succeed to solve this issue?

Thanks!

**Comment by timobrembeck** [comment]
@Roman914 apparently not, so sadly this is not supported by this library I'm afraid.
