### ISSUE TITLE
Switch to a better maintained PyPDF Fork

### ISSUE THREAD

**Issue by captn3m0** [xhtml2pdf/xhtml2pdf#560]
Last commit to https://github.com/mstamy2/PyPDF2 was in 2018.

See https://github.com/mstamy2/PyPDF2/issues/571 and https://github.com/hellerbarde/stapler/issues/78 as well

I'd propose switching to https://github.com/sfneal/PyPDF3 which seems to be better maintained with a few releases this year.

**Comment by dvzrv** [comment]
Hi! Given that the original pypdf2 upstream seems  defunct and I might need xhtml2pdf for rst2pdf (I'm packaging this for Arch Linux), it would be awesome to see some direction on this, as I would like to circumvent packaging pypdf2 if it is in that shape.

**Comment by captn3m0** [comment]
If the project agrees with the PyPDF3 choice, I am happy to start work on a PR.

**Comment by luisza** [comment]
I agree, go a head

**Comment by captn3m0** [comment]
Filed 3 PRs:

- [Switch to PyPDF3](https://github.com/xhtml2pdf/xhtml2pdf/pull/582). This drops support for Python <3.6
- [Remove debug logging from tests](https://github.com/xhtml2pdf/xhtml2pdf/pull/581). This uses `unittest.assertLogs` which needs Python 3.
- [Add GitHub Actions](https://github.com/xhtml2pdf/xhtml2pdf/pull/583). This still needs some work, and can be merged after the above 2 are finalized.

**Comment by dvzrv** [comment]
If there is a chance to get a release with the recent changes, that would be fabulous! <3

**Comment by luisza** [comment]
Yes, I will be a new release soon (one or 2 weeks), but first we need to work more in test, the new release has a lot of changes and dependencies updates.   thanks @captn3m0  for your great work.

**Comment by captn3m0** [comment]
Stuff that I'd like to try to do before the next release:

- [ ] Test improvements for Mac/Windows. Appveyor is very slow, and I'd like to consolidate everything under GitHub Actions
- [ ] Fix coveralls integration. @luisza if you could add 
- [ ] Publishing setup for the docs (also broken currently)
- [ ] A few general test setup improvements
- [ ] Fix render-tests across all platforms, if possible.

None of these are critical as such, so maybe we can push out a beta release in the interim?
