### ISSUE TITLE
Footer content is not displayed

### ISSUE THREAD

**Issue by jorguerra** [xhtml2pdf/xhtml2pdf#564]
I have a footer frame which cannot be seen. This is how I have configured the @frame properties.

```
...
<style type="text/css">
      @page {
        size: A4 portrait; /* can use also 'landscape' for orientation */

        @frame content_frame {          /* Content Frame */
            left: 60pt;
            width: 470pt;
            top: 10pt;
            height: 750pt;
        }
        /* Another static Frame */
        @frame footer_frame {           
            -pdf-frame-content: footer_content;
            left: 60pt; width: 470pt; top: 770pt; height: 40pt;
            display: block;
            color: black;
            -pdf-frame-border: 1; 
        }
      }
</style>
</head>
<body>
<div id="footer_content" style="color:black">My footer </div>
<!-- Rest of the content is being displayed correctly -->
```

In the PDF I can see the pdf frame with the border but empty without any content even though the footer id is the first in being defined after open the body tag.

**Comment by jorenham** [comment]
Is this fixed in 0.2.8?

**Comment by tobiasgardner** [comment]
This works in version 0.2.6 for me, but not any version beyond that.
Same thing with header. As soon as 

            @frame header_frame {
                **-pdf-frame-content:** header_content;
or
            @frame footer_frame {
                **-pdf-frame-content:** footer_content;

is used, those parts of the generated page becomes blank...

**Comment by tyler555g** [comment]
I am having the same issue, but versions 0.2.6 - 0.2.8 do not work.

**Comment by folkvir** [comment]
Same problem, The readthedoc example is only working with `0.2.6` but not higher versions.
Reportlab version: `reportlab==3.6.11`

**Comment by timoludwig** [comment]
What's the status of this issue? Was is closed by merging #628?

**Comment by folkvir** [comment]
@timoludwig 
It seems that the `0.2.9` meets all our requirements and also fixes this issue. 
I confirm that our pdf generated with this new release generates again our footers.

**Comment by timoludwig** [comment]
@folkvir Awesome, thanks for the quick reply!
