### ISSUE TITLE
DeprecationWarning: invalid escape sequence

### ISSUE THREAD

**Issue by maradragan** [xhtml2pdf/xhtml2pdf#568]
I am using xhtml2pdf 0.2.5 with python3.7 and I get the following deprecation warnings:

> /usr/local/lib/python3.7/site-packages/xhtml2pdf/util.py:62: DeprecationWarning: invalid escape sequence \.
>   "^.*?rgb[a]?[(]([0-9]+).*?([0-9]+).*?([0-9]+)(?:.*?(?:[01]\.(?:[0-9]+)))?[)].*?[ ]*$")
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/util.py:615: DeprecationWarning: invalid escape sequence \+
>   b64 = re.sub(b'[^A-Za-z0-9\+\/]+', b'', b64)
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/tags.py:103: DeprecationWarning: invalid escape sequence \:
>   rxLink = re.compile("^(#|[a-z]+\:).*")
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/w3c/cssParser.py:347: DeprecationWarning: invalid escape sequence \s
>   i_unicode = '\\\\(?:%s){1,6}\s?' % i_hex
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/w3c/cssParser.py:350: DeprecationWarning: invalid escape sequence \-
>   i_nmstart = _orRule('\-[^0-9]|[A-Za-z_]', i_nonascii,
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/w3c/cssParser.py:362: DeprecationWarning: invalid escape sequence \*
>   i_element_name = '((?:%s)|\*)' % (i_ident[1:-1],)
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/w3c/cssParser.py:364: DeprecationWarning: invalid escape sequence \*
>   i_namespace_selector = '((?:%s)|\*|)\|(?!=)' % (i_ident[1:-1],)
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/w3c/cssParser.py:379: DeprecationWarning: invalid escape sequence \s
>   i_uri = ('url\\(\s*(?:(?:%s)|((?:%s)+))\s*\\)'
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/w3c/cssParser.py:393: DeprecationWarning: invalid escape sequence \?
>   i_unicoderange2 = "(?:U\\+\?{1,6}|{h}(\?{0,5}|{h}(\?{0,4}|{h}(\?{0,3}|{h}(\?{0,2}|{h}(\??|{h}))))))"
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/w3c/cssParser.py:399: DeprecationWarning: invalid escape sequence \/
>   i_comment = '(?:\/\*[^*]*\*+([^/*][^*]*\*+)*\/)'
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/w3c/cssParser.py:401: DeprecationWarning: invalid escape sequence \s
>   i_important = '!\s*(important)'

**Comment by sguldemond** [comment]
My colleague posted this issue. I tested it with v0.2.7 and it this `DeprecationWarning` no longer appears.
@luisza this issue can be closed.
