### ISSUE TITLE
`ResourceWarning: unclosed file`

### ISSUE THREAD

**Issue by maradragan** [xhtml2pdf/xhtml2pdf#569]
I am using xhtml2pdf 0.2.5 with python3.7 and I get the following  warnings:

> /usr/local/lib/python3.7/site-packages/xhtml2pdf/w3c/css.py:891: ResourceWarning: unclosed file <_io.TextIOWrapper name='<here_path_to_file>' mode='r' encoding='UTF-8'>
>   return cssParser.parseExternal(import_)
> 
> /usr/local/lib/python3.7/site-packages/xhtml2pdf/parser.py:643: ResourceWarning: unclosed file <_io.BufferedReader name='<here_path_to_file>'>
>   pisaLoop(nnode, context, path, **kw)

**Comment by pb-dod** [comment]
@maradragan You're sure you're seeing these errors on python 3.7? I'm only seeing them on 3.8.
