### ISSUE TITLE
`>` not supported between instances of `NoneType` and `float`

### ISSUE THREAD

**Issue by essadek** [xhtml2pdf/xhtml2pdf#573]
- The error above on Windows 10 64bit / Python 3.7.7.
- The html is an output from Pandas pivot table.
-  The error does occur in some cases. however is never occurs on Debian 10 / Python 3.7.3

Requirement already satisfied: xhtml2pdf==0.2.5 in c:\python37\lib\site-packages (0.2.5)
Requirement already satisfied: html5lib>=1.0 in c:\python37\lib\site-packages (from xhtml2pdf==0.2.5) (1.1)
Requirement already satisfied: pyPdf2 in c:\python37\lib\site-packages (from xhtml2pdf==0.2.5) (1.26.0)
Requirement already satisfied: Pillow in c:\python37\lib\site-packages (from xhtml2pdf==0.2.5) (8.3.2)
Requirement already satisfied: reportlab>=3.3.0 in c:\python37\lib\site-packages (from xhtml2pdf==0.2.5) (3.6.1)
Requirement already satisfied: six in c:\python37\lib\site-packages (from xhtml2pdf==0.2.5) (1.14.0)
Requirement already satisfied: python-bidi>=0.4.2 in c:\python37\lib\site-packages (from xhtml2pdf==0.2.5) (0.4.2)
Requirement already satisfied: arabic-reshaper>=2.1.0 in c:\python37\lib\site-packages (from xhtml2pdf==0.2.5) (2.1.3)
Requirement already satisfied: future in c:\python37\lib\site-packages (from arabic-reshaper>=2.1.0->xhtml2pdf==0.2.5) (0.18.2)

<html><body>

Exception Type: | TypeError
-- | --
'>' not supported between instances of 'NoneType' and 'float'
C:\Python37\lib\site-packages\reportlab\platypus\tables.py, line 421, in identity

</body>
</html>

**Comment by timoludwig** [comment]
@essadek Could you provide more information on how to reproduce this problem, e.g. the html code you're trying to render?

**Comment by timobrembeck** [comment]
@essadek without further information, we will not be able to work on this issue.
Also, since the error happened in the `reportlab` library, please report your problem here instead: https://groups.google.com/g/reportlab-users
