### ISSUE TITLE
Python3.9 support

### ISSUE THREAD

**Issue by SteveTr97** [xhtml2pdf/xhtml2pdf#575]
Hi guys, are you planning to support Python3.9 anytime soon in the future?

**Comment by luisza** [comment]
Yes, I am planning to add Python3.9 support and drop Python2 soon, I hope new version will be ready in December

**Comment by AthulYobota** [comment]
Hi @luisza 

Sorry to be a pain, but is there any update on the Python 3.9 support? 😅 

Thanks

**Comment by luisza** [comment]
Hi, please check in the master branch (now It's working with 3.9 and 3.10), when we finish the test new release will launch.

**Comment by luisza** [comment]
Release 0.2.6 support new versions of python 3.
