### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [xhtml2pdf/xhtml2pdf#580]
Hey there!

I belong to an open source security research community, and a member (@srikanthprathi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by captn3m0** [comment]
cc @luisza

**Comment by luisza** [comment]
His, sorry the delay in answer, I create a security policy (and SECURITY.md file), also you can contact me at luisza14 {at} gmail.com, I will see your issue as soon I can.

**Comment by JamieSlome** [comment]
@luisza - I will get that sent to your e-mail shortly - thanks for the response! ⚡ 

Just for reference, the report can be found directly here:
https://huntr.dev/bounties/725e2c5c-594e-4802-a30e-41c6cd64384e/

**Comment by captn3m0** [comment]
@JamieSlome Could you share the report with me as well please? I logged in via huntr.dev, but I don't seem to have access.

**Comment by JamieSlome** [comment]
@captn3m0 - are you sure you have push access to the repository?

I'd recommend visiting the URL again and just refreshing. Let me know if this does not work for you ❤️

**Comment by JamieSlome** [comment]
I have also sent an e-mail to the address stated in the `SECURITY.md`.
