### ISSUE TITLE
getBytesIO and getStringIO are eliminated from reportlab starting v3.6.7

### ISSUE THREAD

**Issue by superdtx** [xhtml2pdf/xhtml2pdf#591]
https://hg.reportlab.com/hg-public/reportlab/rev/cdb9ddeac15a
getBytesIO and getStringIO are eliminated from reportlab starting v3.6.7

**Comment by bschollnick** [comment]
Yep.  Just got bit by this one as well.

**Comment by escomputers** [comment]
Me too! 
Is getStringIO an important function for xhtml2?

**Comment by luisza** [comment]
Yes, the possible release date is March 2.   :).

**Comment by luisza** [comment]
Nop, but try to update from master branch, now it's fixed.

**Comment by Gooliver2** [comment]
@luisza so what's the latest version of the lib that we can use? I see updates in master but seems like I'm missing an appropriate tag for this fix.
