### ISSUE TITLE
Error to import getStringIO from reportlab.lib.utils

### ISSUE THREAD

**Issue by markflorence728** [xhtml2pdf/xhtml2pdf#595]
Hello, how are you?
I am getting error with xhtml2pdf library nowadays.
`ImportError: cannot import name 'getStringIO' from 'reportlab.lib.utils' (/usr/local/lib/python3.9/site-packages/reportlab/lib/utils.py)`

Yeah, I found that reportlab library was upgraded on 18th of February. I am sure the error is occurring with this package upgrading.
Can you please check and fix it as soon as possible?

Regards,
Mark

**Comment by potasiak** [comment]
As a quick fix you can pin reportlab to version 3.6.6.

I highly doubt there will be a fix in xhtml2pdf anytime soon, given the latest release was in January 2020.

**Comment by markflorence728** [comment]
Thank you.

**Comment by masarliev** [comment]
There is fix #590 and merged. @LegoStormtroopr can you release new version with the fix?

**Comment by luisza** [comment]
New version 0.2.6  comes with a fix for it
