### ISSUE TITLE
New release version?

### ISSUE THREAD

**Issue by xdekasx** [xhtml2pdf/xhtml2pdf#597]
Will there be any new release version available in PyPI? 

Some improvements and fixes are in the master branch but are not updated from the pip installation. The last one in PyPI is 0.2.5, dated on October 2020.

Thanks in advance,

**Comment by xdekasx** [comment]
Perfect, thank you very much for answering and for keeping the project up to date.

**Comment by luisza** [comment]
Today I release a new version  0.2.6 .   
Happy coding.

**Comment by xdekasx** [comment]
Nice, thank you!!
