### ISSUE TITLE
Add support for `word-wrap` CSS property

### ISSUE THREAD

**Issue by alispa** [xhtml2pdf/xhtml2pdf#601]
It would be very handy to have support for the CSS ` word-wrap` property. Especially for `word-wrap: break-word;` which would tables and cells make much more reliable.

**Comment by rads92stx** [comment]
Agree on that!

**Comment by timoludwig** [comment]
Duplicate of #379 and #339

**Comment by sneharane588** [comment]
word-wrap property is not supported.
However, " -pdf-word-wrap: CJK;" only works for few of the HTML data samples for me.
