### ISSUE TITLE
throw an invalid filename when using local assets

### ISSUE THREAD

**Issue by sinkaroid** [xhtml2pdf/xhtml2pdf#602]
Hi, how to using local image instead image url?  
I've tried with inside folder and do it with relative path `<img src="/img.jpg"/>` also `<img src="./2.jpg"/>` throwing:  
```Need a valid file name```
When i just pass it with `<img src="img.jpg"/>` it's working but the output is just blank pdf 

It's working properly when using links from url, but i don't want to regenerate the images again from internet

**Comment by Jan-Heussner** [comment]
I have the same issue in my Django Env. I am using the link_callback method and i think he is returning the correct path but i get the same error "Need a valid file name".

**Comment by luisza** [comment]
Yes confirmed.  I will fixed on V0.2.7, I hope I released on next week.

**Comment by luisza** [comment]
Please check new release, that was fixed.

**Comment by Jan-Heussner** [comment]
Yes everything fine now :) Thanks!
