### ISSUE TITLE
white background instead of transparent

### ISSUE THREAD

**Issue by benedikt-bartscher** [xhtml2pdf/xhtml2pdf#605]
Hi there, since v0.2.6 i always get a white background behind all Texts, switching back to 0.2.5 resolves this

**Comment by benedikt-bartscher** [comment]
Thanks for your quick response, i am also interested in a fast release of 0.2.7. Without the changes in 0.2.6 i cannot update reportlab.

This problem applies to all of our documents (over 1000 different HTML Codes). We create multiple PDFs and combine some pages via PyPDF3. With version 0.2.5 the backgrounds were transparent but with 0.2.6 they are white which leads to overlapped parts in the merged PDFs.

The following example only consists of <p> tags, nothing else.
Here's an example screenshot with v0.2.6:
![image](https://user-images.githubusercontent.com/31854409/159991853-6329a221-bfd7-4fb0-bc81-90fb8333c9f8.png)

and here's the same example with only xhtml2pdf changed to v0.2.5:
![image](https://user-images.githubusercontent.com/31854409/159993726-029cf46c-47da-418e-babd-a60bec8168b7.png)

**Comment by luisza** [comment]
Please check the new release, read the new options for watermark.

**Comment by benedikt-bartscher** [comment]
i tried with `background-opacity: 0` but it doesnt work. I dont want to specify an image background, i just want it transparent as it was in 0.2.5.

**Comment by benedikt-bartscher** [comment]
Should i just set an empty SVG as background or is there a clean way?

**Comment by luisza** [comment]
Nop, svg is not supported in background, best is use PNG with alpha channel.  Background opacity is build with pillow, so we process the image setting opacity before build a pdf and then merge first page with the current page.

if you use pdf as background be worry that pages have the same size and page background is transparent

**Comment by benedikt-bartscher** [comment]
No offence but i would still consider this as a bug. I think its unexpected behaviour to get a white (non-transparent) background if no background is specified.

If you really want this, it should be mentioned in the Changelog, as its a breaking change for some users.

Can you reopen this issue?

**Comment by macmoritz** [comment]
I experienced the same issue. 
Obviously should a png have an transparent background. But the text does not have a transparent background since 0.2.6. Before this release text had an transparent background in merged pdfs.
This is a breaking change (which we need to get informed about) or, if the behaviour is unexpected, a bug and closing an ticket does not fix an bug.
