### ISSUE TITLE
Error: `cannot find ft2build.h` while installing xhtml2pdf

### ISSUE THREAD

**Issue by EliasOPrado2** [xhtml2pdf/xhtml2pdf#612]
I am using Docker and I am not being able to install xhtml2pdf. 

```
 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      ##### setup-python-3.9.10-linux-x86_64: ================================================
      ##### setup-python-3.9.10-linux-x86_64: Attempting build of _rl_accel
      ##### setup-python-3.9.10-linux-x86_64: extensions from 'src/rl_addons/rl_accel'
      ##### setup-python-3.9.10-linux-x86_64: ================================================
      ##### setup-python-3.9.10-linux-x86_64: ===================================================
      ##### setup-python-3.9.10-linux-x86_64: Attempting build of _renderPM
      ##### setup-python-3.9.10-linux-x86_64: extensions from 'src/rl_addons/renderPM'
      ##### setup-python-3.9.10-linux-x86_64: ===================================================
      ##### setup-python-3.9.10-linux-x86_64: will use package libart 2.3.21
      !!!!! cannot find ft2build.h
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Is there any other version that can work with linux?

**Comment by TheWilsonDelta** [comment]
Same error here

**Comment by davidncuba** [comment]
Same error

**Comment by timoludwig** [comment]
Is there any more information about what dependency exactly needs `libart` or `ft2build.h` for that matter? I mean it's not a direct dependency of `xhtml2pdf`, so I'm not sure what we can do on our end to prevent this. Maybe a platform-specific sub-dependency? But we'd need more information to reproduce this and offer a solution.

**Comment by lawrencelogoh** [comment]
I have a similar issue #694 . The specific dependency is reportlab. To reproduce this, you can try to install xhtml2pdf on a minimal Linux distribution(like Alpine) that doesn't have freetype installed or installs it in a non-standard location.

**Comment by stefan6419846** [comment]
*reportlab* and *xhtml2pdf* are two different projects, although *xhtml2pdf* uses *reportlab*. You should probably seek support at the *reportlab* user forum instead of here, as we cannot do anything about *reportlab* issues.

**Comment by timobrembeck** [comment]
I'll repeat myself:

> @stefan6419846 Thanks a lot for your support in issue triage, I agree that this has nothing to do with xhtml2pdf.
> 
> Unfortunately, I don't see a clear way how to report bugs for reportlab, there is the repository https://hg.reportlab.com/hg-public/reportlab but I don't see a way to report bugs there. Maybe via the google group https://groups.google.com/g/reportlab-users?

– https://github.com/xhtml2pdf/xhtml2pdf/issues/694#issuecomment-1742058956
