### ISSUE TITLE
background-image renders on top of other content

### ISSUE THREAD

**Issue by direvus** [xhtml2pdf/xhtml2pdf#614]
I use a background-image on the `@page`.  In the past this has worked fine, but as of xhtml2pdf 0.2.7, the image now renders on top of all the other content, and because my image is fully opaque, that means none of the content is visible.

For what it's worth, I think that a CSS property named "background-image" should render the image in ... well, in the background :)

Reverting to 0.2.6 solves the problem for me.

**Comment by waqarprixite** [comment]
@direvus I am getting the image as this, I want to remove the background fo the text, any directions ?
![image](https://user-images.githubusercontent.com/97530277/172387039-bf05bfbc-2541-48f3-a6fa-af5ce66a9ecd.png)

**Comment by Waqar-SE** [comment]
Hi, can you help me remove this white background
![image](https://user-images.githubusercontent.com/36355455/172389937-7e4ad261-5197-43b6-901d-46754a1204e0.png)

**Comment by flash716** [comment]
I am seeing the background-image rendered on top of all content as well.

**Comment by denangeles** [comment]
The background-image: url('') works in 0.2.6, but only displays the background image on the first page.
Downgrading further to 0.2.5 works as expected and renders the background image on all pages.

**Comment by setoria** [comment]
I have the same issue with version 0.2.8. The background-image works again but all the other elements appear with a white background. Can you help me?
![grafik](https://user-images.githubusercontent.com/43284366/174163450-45a95c5a-e266-40a4-9689-4ab5797caab8.png)

**Comment by benedikt-bartscher** [comment]
> I have the same issue with version 0.2.8. The background-image works again but all the other elements appear with a white background. Can you help me? ![grafik](https://user-images.githubusercontent.com/43284366/174163450-45a95c5a-e266-40a4-9689-4ab5797caab8.png)
> 
> I recognised when I use table html Elements background becomes transparent again.

related to https://github.com/xhtml2pdf/xhtml2pdf/issues/605

**Comment by tanveerabid** [comment]
Hi

I have achieved a solution by editing default.py from xhtml2pdf. 

**Background of Problem:**
Parser.py use's `def getColor(value, default=None):

    if value is None:
        return
    if isinstance(value, Color):
        return value
    value = str(value).strip().lower()
    if value == "transparent" or value == "none":
        return default
    if value in COLOR_BY_NAME:
        return COLOR_BY_NAME[value]
    if value.startswith("#") and len(value) == 4:
        value = "#" + value[1] + value[1] + \
            value[2] + value[2] + value[3] + value[3]
    elif rgb_re.search(value):
        r, g, b = [int(x) for x in rgb_re.search(value).groups()]
        value = "#%02x%02x%02x" % (r, g, b)
    else:
        pass

    return toColor(value, default)  # Calling the reportlab function
`
 method in xhtml2pdf which is resided in util.py, has a condition, that if user set background-color: transparent;  than simply replace background color with #ffffff(white Background Color).
as p element by default doesn't support background-color property in xhtml2pdf. so while parsing CSS p element inherits default HTML attributes where default background-color property is set to transparent. which invokes if statement in parser.py via util.py & changes it background to white.
![Screenshot from 2022-07-24 15-00-55](https://user-images.githubusercontent.com/81469212/180642018-a3e6f03b-e39b-427d-89f0-d3c644889307.png)
![Screenshot from 2022-07-24 15-46-41](https://user-images.githubusercontent.com/81469212/180643640-279f035a-a919-4fec-ad57-edf6ab5c49e2.png)

>To overcome this firstly add background-color attribute to p element in default.py so it can support background color next time.  
![Screenshot from 2022-07-24 15-12-24](https://user-images.githubusercontent.com/81469212/180642464-916a3f02-86df-4faf-8eb2-3d71f512d8b4.png)
Then remove 

> background-color: transparent; attribute of HTML element from DEFAULT_CSS  variable in default.py file.

![Screenshot from 2022-07-24 15-17-12](https://user-images.githubusercontent.com/81469212/180642700-c2847e4a-9521-4c6b-98b1-089166a67570.png)
i have already removed it. 

> now its all done.
now if you want transparent background just simply don't used background-color: transparent; as it revokes if statement to change background color to white. you can set any other color by passing it value(avoid using transparent).

> HTML elements by default have transparent background color. here if statement is setting background color to white
>we can get transparent background by removing if statement but there 's a catch that you cannot set any other background color as this statement handles the both. then if someone set background color to transparent it throws error.

I added many custom attributes in default.py and these are working fine and also added a card size page of 86mm x 54mm by editing reportlab, so you can do customization just keep track of then to redo changes in case of error.

Have a good day.

**Comment by timoludwig** [comment]
I think this was probably implicitly resolved by commit 225ad7fc769c504b0dfad64f154a0b860b60679b.
If the issue still persists, please let us know.
