### ISSUE TITLE
Are emojis supported ? Black squares are appearing

### ISSUE THREAD

**Issue by ThaNico** [xhtml2pdf/xhtml2pdf#616]
Hello,

I am using the version 0.2.6 and the command line tool with a simple html snippet (see below)
The snippet contains an emoji and it's equivalent html entity, the html file is encoded as UTF-8
The browser has no issue displaying the emojis : 
![image](https://user-images.githubusercontent.com/9906385/170223674-91f38961-0eb6-43ed-b79e-ecf667748e29.png)

But when I use the tool to convert, the resulting PDF has black boxes for both characters : 
![image](https://user-images.githubusercontent.com/9906385/170223891-8a755325-bd9e-45bc-904f-a59b676b4af9.png)

I tried to set a font-family with some of the defaults indicated in the docs (even tried an asian font) but no luck
Am I doing it wrong or is there no support currently ?

(Btw I have the same issue via python so that's why I tried with the command tool)

Thanks

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body>
  <br>AAA
  😀
  <br>BBB
  &#128512;
</body>
</html>
```

![image](https://user-images.githubusercontent.com/9906385/170224289-0af990bc-aef6-46aa-aa30-5b9269a0bcd3.png)

**Comment by timoludwig** [comment]
Aren't emojis just normal utf-8 characters? So I don't think they are any different from other special alphabets. Just use a custom font which supports these and you should be good to go.
If you're still struggling with this, please provide more information on which font you tried so we can try to reproduce this.
