### ISSUE TITLE
Add support for `border-radius` CSS property

### ISSUE THREAD

**Issue by pedro-jmanuel** [xhtml2pdf/xhtml2pdf#617]
I'm trying to draw a circle but it doesn't work

.badge {
            height: 100px;
            width: 100px;
            display: table-cell;
            text-align: center;
            vertical-align: middle;
            border-radius: 50%; /* may require vendor prefixes */
            background: yellow;
        }

**Comment by vivekdotbaruah** [comment]
@pedro-jmanuel Here is a list of CSS properties supported by **xhtml2pdf** [link](https://xhtml2pdf.readthedocs.io/en/latest/reference.html#supported-css-properties)

**Comment by timoludwig** [comment]
Duplicate of #542

**Comment by crhea93** [comment]
Hi,
 I've run into the same issue. This is a very basic feature that should be added. Not having this option is very prohibitive.
