### ISSUE TITLE
<pdf:pagecount> is not working with 0.2.7

### ISSUE THREAD

**Issue by genglert** [xhtml2pdf/xhtml2pdf#618]
Hi,
I've updated my version of 'xhtml2pdf' from 0.2.6 to 0.2.7 with pip (so the dependencies should be up-to-date), and now the tag `<pdf:pagecount>` (or `<pdf:pagecount />`) makes all the content of the surrounding tag disappear. If `<pdf:pagecount>` is a direct child of `<div id="footer_content">`, all the footer disappears. If I add a surrounding `<div>` tag, only this last one disappears.

Notes:
 -  `<pdf:pagenumber>` (and `<pdf:pagenumber />`) still works fine.
 - I've "updated" to 0.2.6 and it works again (versions of the other libs did not changed when I rolled back).

Have a good day!

**Comment by timoludwig** [comment]
What's the status of this issue? Was is closed by merging #628?

**Comment by genglert** [comment]
Fixed in version 0.2.9.
Thx !
