### ISSUE TITLE
Solution for arabic issues

### ISSUE THREAD

**Issue by Anoirwork** [xhtml2pdf/xhtml2pdf#621]
Hi there, 
i've been looking here and there for solution for arabic issues and i had made sort of multiple solutions.
so if you're having Black boxes :
you need to change the font and make it's path absolute like so 
`@font-face {
      font-family: RTLFont;
      src: url('/home/user/projects/python/tribunal/static/fonts/DejaVuSans.ttf')
    }
    body {
      font-weight: 600;
      font-size: 16px;
      font-family: RTLFont;
      text-align: right;
    }`

if you're having an issue with a character who isn't displaying and instead you're having an empty rectangle in it's place you need to encoding='UTF-8' to your function of pdf generation like so : 
` pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result, --->encoding='UTF-8'<---)`
hope this helps anyone in future.

**Comment by timoludwig** [comment]
@Anoirwork Thanks for your hints. I think the usage of custom fonts is already explained in the docs and the default encoding for `pisaDocument` should be `utf-8` anyway, so I'm going to close this.
