### ISSUE TITLE
How to setup pdf version?

### ISSUE THREAD

**Issue by philipmoniaga** [xhtml2pdf/xhtml2pdf#624]
Is it possible to setup pdf version like 1.7 or add metadata using xhtml2pdf while rendering it from html using pisaDocument?

**Comment by luisza** [comment]
Yes, use  `context_meta` to provide some metadata.

https://github.com/xhtml2pdf/xhtml2pdf/blob/35014fc2e93ca5fd30fa2a7e947c386fb8457fab/xhtml2pdf/document.py#L94
