### ISSUE TITLE
`ImportError: Symbol not found` on Mac OS

### ISSUE THREAD

**Issue by skravi1996** [xhtml2pdf/xhtml2pdf#625]
Referenced from: /Users/skravi/Desktop/logisticsProject/env/lib/python3.10/site-packages/reportlab/graphics/../.dylibs/libpng16.16.dylib
  Expected in: /usr/lib/libz.1.dylib
 in /Users/skravi/Desktop/logisticsProject/env/lib/python3.10/site-packages/reportlab/graphics/../.dylibs/libpng16.16.dylib

if i'm use the Xhtml2pdf python library
![Screen Shot 2022-07-25 at 9 20 15 PM](https://user-images.githubusercontent.com/42066698/180822333-9848cc12-7797-44ef-94e9-a2a1769e0500.png)

**Comment by stefan6419846** [comment]
How is this related to *xhtml2pdf*? This seems like a *reportlab* issue which should posted to their discussion forum if support is required.

**Comment by timobrembeck** [comment]
I agree, @skravi1996 if your issue still exists, please ask for help at https://groups.google.com/g/reportlab-users
