### ISSUE TITLE
State of testrender

### ISSUE THREAD

**Issue by kvdb** [xhtml2pdf/xhtml2pdf#63]
I ran testrender/testrender.py

Seems the generated results have a transparent background, where the reference images do not. That's causing a big difference. Should the reference images be re-rendered to adjust to the new (transparent) situation, or is it not supposed to be like that?

As a sidenote, the generated result was that much different than the reference image, it wouldn't fit in an int:

    diff_value = int(result.strip())

should be:

    diff_value = float(result.strip())

**Comment by benjaoming** [comment]
The line referred to seems to have changed, assuming someone put thought into it :)
