### ISSUE TITLE
background image opacity error with django

### ISSUE THREAD

**Issue by iamuseful** [xhtml2pdf/xhtml2pdf#634]
**Exception Value:** handle_pageBegin args=() [Errno 13] Permission denied: 'C:\\Users\\USER\\AppData\\Local\\Temp\\tmpx0tw3rx0.png'

**Exception Type:** PermissionError
**Django Version:** 4.1.1
**Python Version:** 3.10.7

**Comment by timoludwig** [comment]
How is this error related to the background image opacity? Can you post a minimal example which causes this error?

**Comment by timobrembeck** [comment]
@iamuseful without further information, we will not be able to work on this issue.
Please add more insight in case the problem still exists.
