### ISSUE TITLE
 Inline Icons in PDF export broken

### ISSUE THREAD

**Issue by charludo** [xhtml2pdf/xhtml2pdf#636]
(The issue description is copied from [digitalfabrik/integreat-cms#1537](https://github.com/digitalfabrik/integreat-cms/issues/1537))

### Describe the Bug
When using icons within a line of text, the PDF export creates a white bar across the icon/image with the height of the text line. If the icon itself has about the height of the text, then the icon is mostly invisible. See https://integreat.app/testumgebung/de/alltag/information as an example.

### Steps to Reproduce

1. Create a page with an icon at the beginning and another in the middle of a line of text.
2. Save the page and export a PDF
3. See that the icon at the beginning of the line is fully visible, while the icon in the middle is partially hidden:
  ![image](https://user-images.githubusercontent.com/15197000/172789546-d0350844-5b54-435b-bc8f-8634c1891a6d.png)
### Expected Behavior
Icons/images should be visible regardless of their position in text.

### Actual Behavior
Only images at the beginning or outside of text work as expected.

**Comment by mujeeb91** [comment]
I'm facing the same issue, thanks for fixing it @charludo .
Can you please tell me when this fix will be released? Meanwhile, is there a workaround that I can use for this?

**Comment by charludo** [comment]
@mujeeb91 I think the corresponding PR is already merged, I don't know when it'll make it into a release, sorry

**Comment by timoludwig** [comment]
I think @luisza is the only person with the permissions to create new releases at the moment.

**Comment by charludo** [comment]
@mujeeb91 in the mean time, [here](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/utils/pdf_utils.py#L115) is one possible workaround.

**Comment by luisza** [comment]
Hi, I can make a new release next week end if you considered that it's an important change.

**Comment by mujeeb91** [comment]
> Hi, I can make a new release next week end if you considered that it's an important change.

@luisza thanks but it's no longer urgent. I used the workaround shared by @charludo and the PDF is being generated with icons now.

Thanks for the speedy responses and support!
