### ISSUE TITLE
AttributeError: 'ParaLines' object has no attribute 'lineBreak'

### ISSUE THREAD

**Issue by charludo** [xhtml2pdf/xhtml2pdf#642]
See digitalfabrik/integreat-cms#1498 for a thorough discussion.
It appears this only happens in RTL languages.

**Comment by charludo** [comment]
@luisza would it be possible to create a new release including this fix in the near future? 😃

**Comment by timoludwig** [comment]
@luisza Sorry to bother you again, do you think you could release a new version soon? :heart:
We still see a lot of these errors in our log every day :sweat_smile:
