### ISSUE TITLE
No changelog file

### ISSUE THREAD

**Issue by jkugler** [xhtml2pdf/xhtml2pdf#650]
The README references a changlog file here: https://github.com/xhtml2pdf/xhtml2pdf/blame/master/README.rst#L161 but there is no changelog file in the repository.

**Comment by BergLucas** [comment]
After some research in the git history, I think it has been renamed to `docs/source/release-notes.rst`.

Source : [https://github.com/xhtml2pdf/xhtml2pdf/commits/c9e934d3a853119e965f23740016aca0c5be98b1/CHANGELOG.txt?browsing_rename_history=true&new_path=docs/source/release-notes.rst&original_branch=master](https://github.com/xhtml2pdf/xhtml2pdf/commits/c9e934d3a853119e965f23740016aca0c5be98b1/CHANGELOG.txt?browsing_rename_history=true&new_path=docs/source/release-notes.rst&original_branch=master)

**Comment by jkugler** [comment]
Fantastic, thank you!
