### ISSUE TITLE
`<pdf:pagenumber>` displayed as 0

### ISSUE THREAD

**Issue by sergosamkharadze** [xhtml2pdf/xhtml2pdf#654]
I have noticed that pagenumber and pagecount does not render on html

**Comment by timoludwig** [comment]
Can you provide more insight how to reproduce this problem?

**Comment by timoludwig** [comment]
Ah, you're probably using `<pdf:pagenumber>` outside of `footer_content`, right? Then, this is a duplicate of #546.
