### ISSUE TITLE
Security Vulnerability in xhtml2pdf Dependency "future"

### ISSUE THREAD

**Issue by jacobgqc** [xhtml2pdf/xhtml2pdf#657]
There is a security vulnerability in the future package that does not seem likely to be resolved. Can xhtml2pdf be released to not require this package?
CVE:
https://github.com/advisories/GHSA-v3c5-jqr6-7qm8
Discussions:
https://github.com/PythonCharmers/python-future/issues/612
https://github.com/PythonCharmers/python-future/pull/610

**Comment by timoludwig** [comment]
@luisza Do you think you could release a new version with the updated dependency? Thanks a lot in advance! :pray:

**Comment by luisza** [comment]
Yes, I am working on right now, maybe today or tomorrow i will release a new release.

**Comment by timoludwig** [comment]
@luisza If you would accept help with releasing regular package updates, you can add me (https://pypi.org/user/timoludwig/) or my organization (https://pypi.org/user/digitalfabrik/) as mainatiners of the PyPI package, we'd be happy to invest some working hours :smiley:
