### ISSUE TITLE
Security question. How to disable javascript execution?

### ISSUE THREAD

**Issue by bvsn** [xhtml2pdf/xhtml2pdf#658]
Hi there 👋 There are any ways to pass options to disable javascript execution in the generated PDF? I need to keep strict security for the generated file as for the next PDF options:
```
disable-javascript
disable-external-links
disable-internal-links
disable-local-file-access
```

Also, need to keep my PDF with the `UTF-8` encoding. Thank you.

**Comment by timoludwig** [comment]
Disclaimer: I'm not a maintainer of this package and I'm not 100% about my answers.

- JS in PDF is not supported by this library I think, so no need for `disable-javascript`
- You can disable internal and external links by parsing your HTML input and remove `<a>` tags or their `href` attribute. I think it's probably out of scope to provide that options in the library in my opinion.
- Not sure what you mean by `disable-local-file-access`... when generating the PDF itself, or do you mean there should be no internal links to files in the resulting PDF file? I'm not even sure if that works, but if it does, you could also prevent this by sanitizing your HTML input first.
- The encoding of the PDF should be `UTF-8` in any case? Not sure what you mean by this...

**Comment by bvsn** [comment]
@timoludwig thank you for your response. For encoding I found a default argument from `pisaDocument`:

```
pisa.pisaDocument(bytes, result, encoding="utf-8")
```

Links and JS will escape them manually through default [html.escape](https://docs.python.org/3/library/html.html#html.escape)
