### ISSUE TITLE
New line formatting issue for right-to-left languages

### ISSUE THREAD

**Issue by seluianova** [xhtml2pdf/xhtml2pdf#662]
There is a slight formatting issue for right-to-left languages when a newline is required.

Sample Arabic text with **correct** (expected) formatting:
![image](https://user-images.githubusercontent.com/115008338/214072320-5b186b0a-c33e-4abc-8755-fcd5393cafdb.png)

How it looks in the exported PDF:
![image](https://user-images.githubusercontent.com/115008338/214072654-58baa5fb-43f8-437b-8e03-c1f6078e3fd5.png)

The text itself looks correct (direction and word order), but the shortest line comes first.

**Expected behavior**:
The last line should be the shortest.

**Comment by timoludwig** [comment]
Possibly, this is related to #538.

**Comment by timoludwig** [comment]
@seluianova is this the same problem as described and fixed in #620?

**Comment by seluianova** [comment]
@timoludwig yes!

**Comment by timoludwig** [comment]
This was fixed by f51bf8721233d10adbd4935ec9b6daea5e7af422
