### ISSUE TITLE
Coveralls integration broken

### ISSUE THREAD

**Issue by timobrembeck** [xhtml2pdf/xhtml2pdf#675]
### Describe the Bug

Currently, the coveralls integration is broken (broken badge in the readme as well as broken test coverage link to https://coveralls.io/github/xhtml2pdf/xhtml2pdf).

![badge](https://img.shields.io/coveralls/github/xhtml2pdf/xhtml2pdf?label=Coveralls&logo=Coveralls&logoColor=white)

I'm not sure who is authorized to manage the coveralls integration for this repo, probably only members of the @xhtml2pdf organization?

### Expected Behavior

The Coveralls integration should either be fixed or removed

### Actual Behavior

The badge and links are broken

**Comment by timobrembeck** [comment]
@luisza could you check out what is required here? Or if you add me to the @xhtml2pdf organization I can have a look as well.

**Comment by luisza** [comment]
Hi, I create a coverall account and configure again the coveralls integration, I include on github secret the key for COVERALLS_REPO_TOKEN.

But I don't configure the github actions or other configuration for integrate coverall.
