### ISSUE TITLE
Canvas graph is not working anymore with 0.2.9

### ISSUE THREAD

**Issue by Yorchly** [xhtml2pdf/xhtml2pdf#676]
I think a found a bug rendering canvas graph. I copied the example of canvas with vertical graph in your documentation and no graph is shown, only the json that is included inside canvas' tags. I tried using cli and using code and none of this works for me :(.

### Minimal Example to Reproduce
Create a html with content specified in https://xhtml2pdf.readthedocs.io/en/latest/examples.html#vertical-bars. Then execute cli command (`xhtml2pdf .\template-name.html`) or code (https://xhtml2pdf.readthedocs.io/en/latest/usage.html#using-with-python-standalone) to convert html to pdf.

### Expected Behavior
Pdf with graph. 

### Actual Behavior
Pdf that only contains the json specified inside canvas' tags.

### Additional Information
I have installed xhtml2pdf version 0.2.7 and it works!

### System Information
OS version: Windows 10 Pro 21H2
Python version: 3.11.2
Pip version: 23.0
XHTML2PDF version: 0.2.9

**Comment by daydins** [comment]
We are having the same issue as above. With 2.7, the footer page count tags don't work. So if you need both a canvas graph and a footer in your pdf, you're in a tough spot.

**Comment by daydins** [comment]
I have a workaround locally based on 2.7, but in order to properly track this I'd need a few more days. I'll take a look though!

**Comment by daydins** [comment]
@timoludwig, what's the best way to do this? Should I create a 2.7.1 release with the patch, or track down what happened in 2.9 and go from there?

**Comment by timoludwig** [comment]
@daydins Thanks a lot for your efforts!
I think backporting fixes to older versions is out of scope for this project, in my opinion it would be better to find a patch for the latest release.
Maybe @luisza has more thoughts on this?

**Comment by daydins** [comment]
One of my colleagues fixed it in 2.9 as we were discussing, and he's ready to make a PR! Look out for him :)
