### ISSUE TITLE
Error: `cannot find ft2build.h` while installing xhtml2pdf on OpenBSD

### ISSUE THREAD

**Issue by lawrencelogoh** [xhtml2pdf/xhtml2pdf#694]
### Describe the Bug
ft2build.h is not found while installing xhtml2pdf. 
The specific package that seems to be the culprit is reportlab.
I suspect this error occurs because it's looking for `freetype2/ft2build.h` in `/usr/include/` and not `/usr/X11R6/include/` which is where OpenBSD typically stores it. 

### Minimal Example to Reproduce
- Setup a fresh OpenBSD installation with freetype installed 
- `pip install xhtml2pdf`

### Expected Behavior
The installation occurs without issue.

### Actual Behavior
An error occurs and the installation stops.

### Additional Information

<details>
  <summary>Logs</summary>
<pre>
<code>
Collecting reportlab<4,>=3.5.53
  Using cached reportlab-3.6.13.tar.gz (4.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      ##### setup-python-3.9.16-openbsd-7.3-amd64: ================================================
      ##### setup-python-3.9.16-openbsd-7.3-amd64: Attempting build of _rl_accel
      ##### setup-python-3.9.16-openbsd-7.3-amd64: extensions from 'src/rl_addons/rl_accel'
      ##### setup-python-3.9.16-openbsd-7.3-amd64: ================================================
      ##### setup-python-3.9.16-openbsd-7.3-amd64: ===================================================
      ##### setup-python-3.9.16-openbsd-7.3-amd64: Attempting build of _renderPM
      ##### setup-python-3.9.16-openbsd-7.3-amd64: extensions from 'src/rl_addons/renderPM'
      ##### setup-python-3.9.16-openbsd-7.3-amd64: ===================================================
      ##### setup-python-3.9.16-openbsd-7.3-amd64: will use package libart 2.3.21
      !!!!! cannot find ft2build.h
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

</code>
</pre>
 
</details>

### System Information

OS version: OpenBSD 7.3
Python version: 3.10.11
XHTML2PDF version: 0.2.11

**Comment by stefan6419846** [comment]
*reportlab* and *xhtml2pdf* are two different projects, although *xhtml2pdf* uses *reportlab*. You should probably seek support at the *reportlab* user forum instead of here, as we cannot do anything about *reportlab* issues.

**Comment by timobrembeck** [comment]
@stefan6419846 Thanks a lot for your support in issue triage, I agree that this has nothing to do with xhtml2pdf.

Unfortunately, I don't see a clear way how to report bugs for reportlab, there is the repository https://hg.reportlab.com/hg-public/reportlab but I don't see a way to report bugs there. Maybe via the google group https://groups.google.com/g/reportlab-users?

**Comment by stefan6419846** [comment]
Yes, the only way (unless you are a paying customer) is the Google Group, see https://www.reportlab.com/support/
