### ISSUE TITLE
Clarify license for xhtml2pdf.w3c module

### ISSUE THREAD

**Issue by stefan6419846** [xhtml2pdf/xhtml2pdf#696]
The files inside the `xhtml2pdf.w3c` have file headers like this: https://github.com/xhtml2pdf/xhtml2pdf/blob/c72722b10a345fa0242a9e758809b4cd786120bf/xhtml2pdf/w3c/__init__.py#L3-L9

Digging through the code (big renaming in https://github.com/xhtml2pdf/xhtml2pdf/commit/e8832cc5330ca04bf1a5d8539bce74df07124f46 and history at https://github.com/xhtml2pdf/xhtml2pdf/commits/69b58861b8b5f10efaa59081e7f2670ba2c93453/sx/w3c), it seems like the `LICENSE.txt` file actually is the same as today (https://github.com/xhtml2pdf/xhtml2pdf/commit/881850e49b67d8c9111ac53d09fb90138c1a3320, https://github.com/xhtml2pdf/xhtml2pdf/blob/master/LICENSE.txt)

In my opinion, the corresponding headers should be made more obvious - at least for me Apache-2.0 is not really "BSD style".

**Comment by timobrembeck** [comment]
I'm not an expert on open source licenses, but to me this just seems like a mistake in the original package as you said?
In this case, I think it would be fine to just remove this sentence since the license is already defined in the root directory and does not need to be mentioned again in each module, right?

**Comment by stefan6419846** [comment]
Looking at https://github.com/xhtml2pdf/xhtml2pdf/commit/881850e49b67d8c9111ac53d09fb90138c1a3320#diff-93017bf69c6db885ee88855205dfd4d0d87afee28dca8921ed23660f973e19fc already mentioned above, which was the initial commit, files like `sx.pisa3.pisa_pdf` only carried the copyright of Dirk and had the correct Apache-2.0 headers.

For the `sx.w3c` files, we have by contrast some copyright by TechGame Networks LLC with modifications by Dirk. It sounds like these files might originate from some other open source project and have been incorporated into *xhtml2pdf* with some modifications.

"BSD style License" can generally be each BSD-*n*-Clause license, something like the Apache-1.*n* family etc. or a license with custom conditions - we just do not know for sure. Thus simply removing the offending section does not seem quite right. In the best case, just re-licensing the *xhtml2pdf* version of the files under the Apache-2.0 license as the *xhtml2pdf* project license is possible, but this might depend on the actual "BSD style License" referenced. Maybe @holtwick can say something about this, although 13 years have passed in-between?

As for how to apply licensing to a project (if no thirdparty code has been copied over, which usually imposes additional considerations), there generally are multiple approaches, depending on the preferences of the maintainers. The Linux Foundation recommends to add a (short) license header to each source file with a well-defined license name or SPDX identifier besides the license file at the project root itself.

Disclaimer: IANAL.

**Comment by holtwick** [comment]
Hi there, looks like I need to fig deep in my memories ;) 

Indeed, the w3c/css code doesn't originate from me. I integrated them, because some modifications where needed and wanted to keep the dependencies low. 

But as far as I remember it was published under a BSD like license? IANAL too, but I think the both licenses do not conflict and integration of BSD licensed code should be fine as long as the copyright notice is kept and no advertising with their name is done. 

This might be useful source of info https://softwareengineering.stackexchange.com/questions/40561/is-bsd-license-compatible-with-apache

**Comment by stefan6419846** [comment]
Thanks for the answer. Indeed, BSD-style licenses generally are considered compatible to the Apache-2.0 license. The only thing that might be of interest is whether the license included an advertising clause or not.

Nevertheless, in terms of good license compliance (for example because of some distribution with company code) a correct license name would be great.

**Comment by stefan6419846** [comment]
I did not really expect to actually find something useful as the copyright markers are nearly 20 years old, but skimming through Google, Facebook and the personal homepage of the "TechGame Networks, LLC." founder (https://shaneholloway.com/resume/) I finally ended up on the companys' GitHub profile: https://github.com/techgame

The corresponding files seem to stem from https://github.com/techgame/tg-framework/tree/master/w3c The initial license seems to have been BSD-3-Clause (https://github.com/techgame/tg-framework/commit/1f1ee388b99b40b8d1535f7cf5d146543ff65bcf#diff-d0ed4cc3fb70489fe51c7e0ac180cba2a7472124f9f9e9ae67b01a37fbd580b7), while later being changed to the even more permissive MIT (https://github.com/techgame/tg-framework/commits/master/LICENSE.txt)

For this reason, I would consider the Apache-2.0 for the *xhtml2pdf* fork of the files a valid choice.

**Comment by holtwick** [comment]
Wow @stefan6419846 Good research! 

However, if it helps in any way, I would also be fine with changing my additions to this project from Apache 2 to the MIT license. But I guess Apache 2 should be fine for most use cases anyway.

**Comment by stefan6419846** [comment]
Apache-2.0 should be fine, as it is the general project license anyway and having different licenses in the code base always means additional work for anyone checking compliance. Changing the general project license usually is not feasible as well due to usually requiring the approval of all contributors.

**Comment by timobrembeck** [comment]
Awesome, thank you for clarifying the issue!
@stefan6419846 do you want to open a PR with the license change?

**Comment by stefan6419846** [comment]
Yes, I can have a look at this tomorrow.
