### ISSUE TITLE
Reportlab 4 compatibility

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [xhtml2pdf/xhtml2pdf#699]
Any timeline to be compatible with Reportlab 4?

**Comment by rvanlaar** [comment]
What's the issue with Reportlab 4 compatibility?

I'm using xhtml 0.2.10 and PDFs with reportlab 4.0.4 do render without issue.

**Comment by timoludwig** [comment]
@VelizarVESSELINOV There is no longer an active community developing this project, so there are no timelines for when to expect a particular feature or bugfix.
Could you check if #688 is still relevant or if we can remove the constraint without risking another dependency conflict?

**Comment by VelizarVESSELINOV** [comment]
Any plans to release a new version to PyPI? The current version is 0.2.11 from May 2023

**Comment by timobrembeck** [comment]
@VelizarVESSELINOV Sorry, it will take ~3 weeks until I'll have time for that (not so much for the releasing itself, but to deal with potential bugs that might exist in the current development version).
In the mean time, please install the library directly from git if you're relying on the latest changes.

**Comment by viniciusd** [comment]
> @VelizarVESSELINOV Sorry, it will take ~3 weeks until I'll have time for that (not so much for the releasing itself, but to deal with potential bugs that might exist in the current development version). In the mean time, please install the library directly from git if you're relying on the latest changes:
> 
> ```
> pip install git+https://github.com/xhtml2pdf/xhtml2pdf 
> ```

Do you have an ETA in mind @timobrembeck? I understand the initial 3 weeks were just an initial estimate and you are not bound by that

**Comment by timobrembeck** [comment]
> Do you have a new ETA in mind @timobrembeck? I understand the initial 3 weeks were just an initial estimate and you are not bound by that

@viniciusd I cannot promise, but I will try to release a new version tomorrow! :+1:

**Comment by timobrembeck** [comment]
Version `0.2.12` has now been released, let me know if you face any problems with the new version!
