### ISSUE TITLE
ZeroDivisionError Caused by Empty Table Rows

### ISSUE THREAD

**Issue by milkybee** [xhtml2pdf/xhtml2pdf#70]
If the HTML you send to pisa.CreatePDF() contains "<tr><td></td></tr>" then a ZeroDivisionError exception is thrown. The traceback goes to reportlab/platypus/flowables.py in func, line 951. Removing the empty table row resolves the error.

**Comment by benjaoming** [comment]
The reportlab err is now more understandable

```
  File "xhtml2pdf/lib/python3.4/site-packages/reportlab/platypus/tables.py", line 224, in __init__
    raise ValueError("%s must have at least a row and column" % self.identity())
```
