### ISSUE TITLE
Add readthedocs checks to pull requests

### ISSUE THREAD

**Issue by timobrembeck** [xhtml2pdf/xhtml2pdf#720]
### Motivation

From time to time, merged PRs break the readthedocs build.
It would be better if we could check this beforehand.

### Proposed Solution

- Enable the build of PRs here: https://readthedocs.org/dashboard/xhtml2pdf/advanced/
- Install the readthedocs GitHub app for the @xhtml2pdf organization

### Additional Context

Only members of the @xhtml2pdf organization have the permission to change this.
@luisza could you set up the integration or add me as member of the @xhtml2pdf organization so I can have a look? Thanks!

**Comment by luisza** [comment]
Hi, I enabled the build of PRs and readthedocs app is active in the organization.

**Comment by timobrembeck** [comment]
@luisza Thanks, worked like a charm! :+1:
