### ISSUE TITLE
Debug log wrong format (v. 0.2.12)

### ISSUE THREAD

**Issue by Qusarber** [xhtml2pdf/xhtml2pdf#730]
I have updated xhtml2pdf to version 0.2.12 in my project and after this I'm facing issue with debug log.

- Debug logs is enabled in my project as well as logs from installed packages
- Rollback to version 0.2.10 (previous version I used in project) is resolving this issue.

Part of traceback error is:
```
File "/usr/local/lib/python3.12/site-packages/xhtml2pdf/tables.py", line 353, in start
log.debug("Col %d has width %d", col, width)
Message: 'Col %d has width %d'
Arguments: (2, '45%')
TypeError: %d format: a real number is required, not str
```

Part of code where I use xthml2pdf:
`pisa.CreatePDF(html.encode("utf-8"), dest=file, encoding="utf-8")`

Python version: 3.12
XHTML2PDF version: 0.2.12

**Comment by viniciusd** [comment]
Alike #732, this was caused by some linter refactoring here https://github.com/xhtml2pdf/xhtml2pdf/commit/a3211b854672a09e257d8c4cf7192e30a2690d58

The conversion from the untyped `{}` formatting to `%d` broke due to percentage-related widths, which are strings

**Comment by viniciusd** [comment]
> width = c.frag.paddingLeft + c.frag.paddingRight
@Qusarber do you use `paddingLeft` or `paddingRight`? Are they percentages?

**Comment by timobrembeck** [comment]
@Qusarber @viniciusd Sorry for messing this up, to be honest I don't yet completely understand the code base, I'm slowly trying to grasp the meaning of specific variables and thought using type hints would help me understanding what's going on.
Hopefully, this temporary potential of new bugs will pay off in the long term by getting a code base that is better maintainable.

**Comment by viniciusd** [comment]
> @Qusarber @viniciusd Sorry for messing this up, to be honest I don't yet completely understand the code base, I'm slowly trying to grasp the meaning of specific variables and thought using type hints would help me understanding what's going on. Hopefully, this temporary potential of new bugs will pay off in the long term by getting a code base that is better maintainable.

That’s fine, don’t be hard on yourself. Thanks for stepping up and maintaining it.

I will try to get around the codebase and see if I can help out :)
