### ISSUE TITLE
TypeError on column width expressed as percentage

### ISSUE THREAD

**Issue by JanEgner** [xhtml2pdf/xhtml2pdf#731]
### Describe the Bug
After update to 0.2.12, unit tests involving xhtml2pdf started to fail with TypeError.

### Expected Behavior
xhtml2pdf should work as before

### Actual Behavior
Error with stack trace:

```
        for i, colWidth in enumerate(newColWidths):
            if (colWidth is not None) or (colWidth == "*"):
                newColWidth = self._normWidth(colWidth, totalWidth)
>               remainingWidth -= colWidth
E               TypeError: unsupported operand type(s) for -=: 'float' and 'str'

..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\xhtml2pdf\xhtml2pdf_reportlab.py:832: TypeError

```

Patching the offending line to use `newColWidth` instead of `colWidth` resolves the error.

### System Information
OS version: both Windows 10 and Linux
Python version: 3.10
XHTML2PDF version: 0.2.12

**Comment by viniciusd** [comment]
This bug was caused by a refactoring when the ruff linter was added:

https://github.com/xhtml2pdf/xhtml2pdf/commit/a3211b854672a09e257d8c4cf7192e30a2690d58#diff-74f01775643512741726dc5b4de3062a970be3ce0a07bd148192173000fb872dL822
