### ISSUE TITLE
Wheel contains files & packages it shouldn't

### ISSUE THREAD

**Issue by carlsmedstad** [xhtml2pdf/xhtml2pdf#736]
### Describe the Bug

In addition to the `xhtml2pdf` package, the wheel contains the top-level packages `demo`, `docs` and `testrender` directories. These packages should not be included in the wheel as they are not part of the main package and are likely to be in conflict with any other package that accidentally includes for example a `docs` package.

To test this, build and install the wheel and inspect the installed files:

```sh
python -m build --wheel --no-isolation
python -m installer --destdir="$some_dir" dist/*.whl
ls "$some_dir/usr/lib/python3.11/site-packages/"
```

In the AUR package I maintain, I've included the following patch to fix this issue:

```diff
diff --unified --recursive --text xhtml2pdf-0.2.13.orig/pyproject.toml xhtml2pdf-0.2.13/pyproject.toml
--- xhtml2pdf-0.2.13.orig/pyproject.toml	2023-11-11 11:10:18.591303923 +0100
+++ xhtml2pdf-0.2.13/pyproject.toml	2023-11-11 11:10:58.961431424 +0100
@@ -86,7 +86,13 @@
 version = {attr = "xhtml2pdf.__version__"}

 [tool.setuptools.packages.find]
-exclude = ["tests", "tests.*", "manual_test", "manual_test.*"]
+exclude = [
+  "tests", "tests.*",
+  "manual_test", "manual_test.*",
+  "demo", "demo.*",
+  "testrender", "testrender.*",
+  "docs", "docs.*",
+]


 [tool.tox]
```

### Additional Information

I maintain the [AUR package](https://aur.archlinux.org/packages/python-xhtml2pdf) for xhtml2pdf.

### System Information

OS version: Arch Linux
Python version: 3.11
XHTML2PDF version: 0.2.13

**Comment by stefan6419846** [comment]
Do you want to submit a corresponding PR?

**Comment by carlsmedstad** [comment]
Of course, done!
