### ISSUE TITLE
Wrong image source rendered with link_callback (v. 0.2.12+)

### ISSUE THREAD

**Issue by lpitkorbx** [xhtml2pdf/xhtml2pdf#738]
### Describe the Bug

I'm using **xhtml2pdf** to generate PDF test reports. I have screenshots and other images in the reports that I show.  Recently I noticed that images are quite messed up when I generate reports. For example, below, the "more" image is supposed to be different image (you can see how it is weirdly stretched).
![Screen Shot 2023-11-13 at 2 28 06 PM](https://github.com/xhtml2pdf/xhtml2pdf/assets/122493785/334f45bb-03a9-45e0-b75f-55b418a9162c)

I downgraded to 0.2.11 and it works perfectly fine.

### Minimal Example to Reproduce

Here's the code for minimal example to repro:

```
import os
from io import StringIO
from xhtml2pdf import pisa

dir_path = os.path.dirname(os.path.realpath(__file__))

html_content = """
<html><head></head>
<body>
    <div style="width: 200px; display: inline-block; float: left; vertical-align: top;">
        <span>flower</span>     
        <img src="flower.png">
    </div>
    <div style="width: 200px; display: inline-block; float: left; vertical-align: top;">
        <span>rock</span>     
        <img src="rock.png">
    </div>
    <div style="width: 200px; display: inline-block; float: left; vertical-align: top;"> 
        <span>tree</span>     
        <img src="tree.png">
    </div>
</body>
</html>
"""

with open("report.pdf", "b+w") as file:
    pisa.CreatePDF(StringIO(html_content), dest=file, link_callback=lambda src, *args: f"{dir_path}/{src}")

```

### Expected Behavior

All images render properly (0.2.11):

<img width="957" alt="Screen Shot 2023-11-13 at 2 47 49 PM" src="https://github.com/xhtml2pdf/xhtml2pdf/assets/122493785/4cfae0aa-f670-4e6a-a5d4-2c0e95f676f5">

### Actual Behavior

Images are messed up (0.2.12+):

<img width="959" alt="Screen Shot 2023-11-13 at 2 48 47 PM" src="https://github.com/xhtml2pdf/xhtml2pdf/assets/122493785/71bd5180-8ab3-4806-a8db-747eb8d154dd">

### Additional Information

I think there maybe some sort of scope issue with variables or some caching that is not properly used. I didn't have time to actually dig into it, but it is quite important to report.

### System Information

OS version: Mac M1 - MacOS Monterey
Python version: 3.9.16
XHTML2PDF version: 0.2.12+

**Comment by brox** [comment]
I'm seeing the same problem after a combined upgrade of xhtml2pdf from 0.2.10 to 0.2.13 and reportlab from 4.0.6 to 4.0.7. Rolling back xhtml2pdf to 0.2.10 (but keeping reportlab at 4.0.7) fixed it.

**Comment by VelizarVESSELINOV** [comment]
I also reverted to the old versions to have images in the right spot:
xhtml2pdf==0.2.11
reportlab==3.6.1
There is a mismatch in image indexes mismatch with the new version.

**Comment by Saurabh-Singh-00** [comment]
Facing same issue headers and footer images are some times swapped in some pages. I am using images in header and footer content. The images are swapped in some pages randomly and the behaviour is random.

**Comment by Pietro395** [comment]
I also ran into the same problem with version 0.2.13, the images are randomly swapped.

No problems with version 0.2.11

**Comment by timobrembeck** [comment]
Sorry guys for breaking this, I released version `0.2.14` now and hopefully this should be fixed now, could anybody verify?

**Comment by brox** [comment]
I upgraded from 0.2.10 to 0.2.14 and it works like it should - thanks!

**Comment by Pietro395** [comment]
Thank you @timobrembeck, we tried and it is fixed in the new version
