### ISSUE TITLE
Make `pyCairo` dependency optional

### ISSUE THREAD

**Issue by allanlewis** [xhtml2pdf/xhtml2pdf#741]
### Motivation

Following the release of v0.2.12, this library now depends on pyCairo. This is a problem for AWS Lambda users like myself because the Lambda runtime doesn't include the underlying `cairo` library.

### Proposed Solution

Make the pyCairo dependency optional via an extra so that users can opt-in. (I'm not sure how much refactoring this would entail.)

### Alternatives

I can pin `xhtml2pdf==0.2.11` but that just builds up tech debt for some future date when it becomes incompatible with something else, or when a security vulnerability is reported.

**Comment by stefan6419846** [comment]
This is related to *reportlab* generally recommending the *pycairo* rendering backend instead of the old RenderPM one: https://docs.reportlab.com/install/open_source_installation/

**Comment by timobrembeck** [comment]
@stefan6419846 To be honest, I didn't even try it out if this library could theoretically work without pycairo... Are we generating bitmaps somewhere with xhtml2pdf? :thinking:

**Comment by stefan6419846** [comment]
I am not sure, but we need one of the backends. For RenderPM, I am not sure if this will be dropped at some point in time. It seems to do some T1 font stuff for example, although I have no clear overview over the *reportlab* code. In https://github.com/xhtml2pdf/xhtml2pdf/pull/708#issuecomment-1742137119, I already had some doubts about enforcing *pycairo*.

**Comment by timobrembeck** [comment]
> I am not sure, but we need one of the backends. For RenderPM, I am not sure if this will be dropped at some point in time. It seems to do some T1 font stuff for example, although I have no clear overview over the _reportlab_ code.

Ok, then we just have to keep track of the reportlab release notes, right? And for the moment, we can use it as base?

> In [#708 (comment)](https://github.com/xhtml2pdf/xhtml2pdf/pull/708#issuecomment-1742137119), I already had some doubts about enforcing _pycairo_.

Ah, right, I forgot about that. I'll open a PR for it, I think the extra dependency will be trivial to implement, just a bit irritating for the users who update the version and might not read the release notes, so they potentially miss that they have to explicitly install this extra...

**Comment by stefan6419846** [comment]
> Ok, then we just have to keep track of the reportlab release notes, right? And for the moment, we can use it as base?

Yes, we have to check for the *reportlab* release notes or installation instructions when RenderPM will be dropped. Using as "base" will not work if I understand correctly, as you will always need one of the backends.

**Comment by dwgreen1** [comment]
Just wanted to add that I am having a similar problem now but with Microsoft Azure, which also does not have the right dependencies for cairo. Very similar to AWS. I also have to keep `xhtml2pdf==0.2.11` pinned now.

**Comment by stefan6419846** [comment]
In theory, you should be able to generate custom binary wheels (for example Manylinux ones) for *pycairo* or *cairocffi* (which seems to be preferred by the *reportlab* authors) to be able to use the new Cairo backend in such cases.

**Comment by timobrembeck** [comment]
@allanlewis @dwgreen1 I released version `0.2.14` now, does this fix the issue for you?
As mentioned in the release notes, you might have to install `xhtml2pdf[renderpm]` to make use of the fallback rendering backend instead.

**Comment by allanlewis** [comment]
> I released version `0.2.14` now, does this fix the issue for you?

Yes, that's perfect - thanks!

> As mentioned in the release notes, you might have to install `xhtml2pdf[renderpm]` to make use of the fallback rendering backend instead.

Thanks for the heads-up - I've added that extra and it pulls in `rl-renderpm` which has wheels for all the environments I need 🏆
