### ISSUE TITLE
Breaking changes and versioning

### ISSUE THREAD

**Issue by jorenham** [xhtml2pdf/xhtml2pdf#748]
I noticed that release `0.2.14` comes with a breaking change. 
This caused me quite a bit of trouble, as I was using the version restriction`<0.3.0`, which would be safe with semantic versioning (or something similar).

Is there some sort of versioning policy in place at the moment, so I can prevent future server crashes? And if not, are you open to adopting one (e.g. semantic versioning)?

**Comment by timobrembeck** [comment]
@jorenham I'm sorry about the inconvenience, I think I underestimated the consequences of the release, also given the fact that 0.2.13 already (unintentionally) contained a breaking change for many users and the purpose of version 0.2.14 was to fix this "bug". 
In theory, this project aims at enforcing semantic versioning and such constraints should theoretically work in the future.

**Comment by timobrembeck** [comment]
Maybe the best solution would be to release 0.2.15 with the state of the last non-breaking version and repackage all recent changes as 0.3.0?

**Comment by jorenham** [comment]
You could also yank 0.2.14

**Comment by timobrembeck** [comment]
Well, if we want to be consistent in enforcing version conventions then I would have to yank 0.2.13 as well since it also contains unintended breaking changes...

**Comment by jorenham** [comment]
For the dropped support for Python 3.7 in 0.2.12, I doubt it'll be much of a problem, since you explicitly specified the `requires_python` in the `pyproject.toml`.

**Comment by timobrembeck** [comment]
No, I meant the update to report lab 4 (#708) which made it impossible to install for all users who didn't have cairo installed.

**Comment by timobrembeck** [comment]
@jorenham Apart from that, could you state which error you encountered exactly?
Did any error occur when creating PDFs without installing xhtml2pdf with a rendering backend?

**Comment by timobrembeck** [comment]
@jorenham Oh that's unfortunate. Again, I'm very sorry about the trouble, but I have decided against yanking old versions, since this package was very broken before (and as a matter of fact, still is)... :roll_eyes: 
So I really hope to get a bit more stable maintenance in the future, but for now I'll leave the old versions there :neutral_face:
