### ISSUE TITLE
Accented UTF8 chars are not correctly show in the created PDF

### ISSUE THREAD

**Issue by jcrmatos** [xhtml2pdf/xhtml2pdf#749]
### Describe the Bug
Accented UTF8 chars are not correctly show in the created PDF

### Minimal Example to Reproduce
I have this text in my source HTML in UTF8
Relatório de intervenção
and I'm getting this in the created PDF
RelatÃ³rio de intervenÃ§Ã£o

Another example is this in my source HTML
Teclalivre - Tecnologias de Informação, Lda.
R. José Viana, Lote 12-A - R/C Esq.
Casal Novo  1685-609 CANEÇAS
and I'm getting this in the result PDF
Teclalivre - Tecnologias de InformaÃ§Ã£o, Lda.
R. JosÃ© Viana, Lote 12-A - R/C Esq.
Casal Novo 1685-609 CANEÃ‡AS

### Expected Behavior
I should be getting this
Relatório de intervenção
and this
Teclalivre - Tecnologias de Informação, Lda.
R. José Viana, Lote 12-A - R/C Esq.
Casal Novo  1685-609 CANEÇAS

### Actual Behavior
I tried creating the PDF with and without the encoding parameter but the result is the same.

### Additional Information
I enclose the result PDF and the zipped HTML.

### System Information
OS version: Windows 11 23H2
Python version: 3.10.11
XHTML2PDF version: 0.2.14

[2024-02-03-18-20.pdf](https://github.com/xhtml2pdf/xhtml2pdf/files/14152529/2024-02-03-18-20.pdf)
[report.zip](https://github.com/xhtml2pdf/xhtml2pdf/files/14152528/report.zip)

**Comment by stefan6419846** [comment]
I cannot reproduce this with the `cairocffi` renderer on Ubuntu 22.04 and the following code (mostly copied from the docs):

```python3
from xhtml2pdf import pisa             # import python module

# Define your data
source_html = "<html><body><p>Relatório de intervenção</p></body></html>"
output_filename = "test.pdf"

# Utility function
def convert_html_to_pdf(source_html, output_filename):
    # open output file for writing (truncated binary)
    result_file = open(output_filename, "w+b")

    # convert HTML to PDF
    pisa_status = pisa.CreatePDF(
            source_html,                # the HTML to convert
            dest=result_file)           # file handle to recieve result

    # close output file
    result_file.close()                 # close output file

    # return False on success and True on errors
    return pisa_status.err

# Main program
if __name__ == "__main__":
    pisa.showLogging()
    convert_html_to_pdf(source_html, output_filename)
```

If you are saving the above code into an UTF-8 encoded file, will this change anything?

**Comment by jcrmatos** [comment]
Found the problem. My bad.
Wasn't opening the UTF8 source file using the encoding parameter.
Thanks for the feedback.
