### ISSUE TITLE
broken reportlab import

### ISSUE THREAD

**Issue by jeverling** [xhtml2pdf/xhtml2pdf#751]
Hi, it looks like there was a reportlab release today: https://pypi.org/project/reportlab/4.1.0/#history

This seems to lead to a broken import:

```
File "/usr/local/lib/python3.8/site-packages/xhtml2pdf/context.py", line 30, in <module>
    from reportlab.platypus.frames import Frame, ShowBoundaryValue
ImportError: cannot import name 'ShowBoundaryValue' from 'reportlab.platypus.frames' (/usr/local/lib/python3.8/site-packages/reportlab/platypus/frames.py)
```

Presumably this functionality changed in reportlab.
Maybe it would be a good idea, to pin the version of reportlab more strictly? Right now it's `"reportlab>=4.0.4"`.

**Comment by timreibe** [comment]
+1, seems like this error came with reportlab upgrade to version `4.1.0`

https://pypi.org/project/reportlab/#history

**Comment by MarcusTherkildsen** [comment]
Oh my, another package failing because of a sub-dependency not being handled properly. I hate it so much!

**Comment by timobrembeck** [comment]
Sorry guys for the inconvenience, I pinned `reportlab<4.1` now, hopefully this fixes the issue until we can have a closer look how we can replace the missing reportlab function.

**Comment by timobrembeck** [comment]
> Oh my, another package failing because of a sub-dependency removing functionality. I hate it so much!

I understand your frustration, but please keep in mind that you're using free and open source software, so don't be mad at people who sacrifice a little of their free time to maintain a legacy project.

**Comment by MarcusTherkildsen** [comment]
I understand.

I guess my comment was more geared towards the fact that this happens quite frequently, for various packages. 

Thanks for your efforts

**Comment by stefan6419846** [comment]
`reportlab<4.1` is not sufficient - the change happened in `reportlab==4.0.9.1`: https://hg.reportlab.com/hg-public/reportlab/rev/f639b3f1d8b0 https://hg.reportlab.com/hg-public/reportlab/file/tip/CHANGES.md

The new import seems to be `from reportlab.pdfgen.canvas import ShowBoundaryValue`.
