### ISSUE TITLE
python-bidi 0.5.0 introduces a breaking change

### ISSUE THREAD

**Issue by bengosney** [xhtml2pdf/xhtml2pdf#766]
### Describe the Bug
python-bidi 0.5.0 introduces a breaking change

### Minimal Example to Reproduce
Install python-bidi 0.5.0 and run the test suit

**Comment by FunksMaName** [comment]
Pending merging the linked PR, I unblocked my project by uninstalling python-bidi-0.5.0 and installing the last compatible version `pip install 'python-bidi>=0.4.2,<0.5.0'`

**Comment by jorenham** [comment]
I believe that `python-bidi 0.6.0` fixes this:
https://github.com/MeirKriheli/python-bidi/releases/tag/v0.6.0

**Comment by ffissore** [comment]
I can confirm that our code works fine after an update to its venv: python-bidi==0.6.0 was downloaded this time and it works fine
