### ISSUE TITLE
Dependency/python-bidi: removed  Removed algorithm.py from python-bidi package

### ISSUE THREAD

**Issue by kiran1415** [xhtml2pdf/xhtml2pdf#770]
### Describe the Bug

removed the algorithm.py from python-bidi module and we have import at xhtml2pdf/util.py line 25
so we need to replace the 
`from bidi.algorithm import get_display
` with
`from bidi import get_display
`

XHTML2PDF version:v0.2.16
python-bidi Version: 0.5.0

**Comment by stefan6419846** [comment]
Duplicate of #766.
