### ISSUE TITLE
The _parseAt* functions consume one too many characters which can cause problems with minified CSS

### ISSUE THREAD

**Issue by mrphang** [xhtml2pdf/xhtml2pdf#88]
In _parseAtPage, for example, the line

src = src[len('@page '):].lstrip()

will throw a ParseError for the following valid css

@page{/*...*/}

**Comment by timoludwig** [comment]
Since this issue is about all `_parseAt*` functions but was only fixed for the `_parseAtPage` function, I suggest to reopen this issue.
The problem with minified CSS still exists in the following functions:
- `_parseAtMedia`
- `_parseAtFrame`
- `_parseAtFontFace`
