### ISSUE TITLE
How to implement setCharSpace for letter-spacing

### ISSUE THREAD

**Issue by tachang** [xhtml2pdf/xhtml2pdf#89]
ReportLab in the documentation:
http://www.reportlab.com/docs/reportlab-userguide.pdf

has this method:

textobject.setCharSpace(charSpace)

I am trying to implement it but for some reason even in line 1618 of reportlab_paragraph.py I hardcode the method tx.setCharSpace(10)  and then it calls canvas.drawText(tx) I am still not seeing it go through. Chris maybe you have some better ideas?

**Comment by fbernhart** [comment]
Letter spacing has been implemented some years (?) ago.

@luisza Please close this one.
